import assert from 'node:assert/strict';
import test from 'node:test';
import {parseSql} from '../../src/internal/parse.ts';
import {expandAndResolveSelect,NameResolutionError} from '../../src/internal/resolve.ts';
const column=(name,declaredType=null,affinity='blob',collation=null)=>Object.freeze({name,declaredType,affinity,collation});
const table=(name,columns,primaryKey=[])=>{columns=Object.freeze(columns);return Object.freeze({kind:'table',name,tableName:name,rootPage:2,sql:'',columns,indexes:Object.freeze([]),withoutRowid:false,primaryKey:Object.freeze(primaryKey.map(i=>columns[i])),storageKey:Object.freeze([])})};
const schema={tables:new Map([['a',table('a',[column('x','INTEGER','integer'),column('same','TEXT','text','NOCASE')])],['b',table('b',[column('x','REAL','real'),column('y','TEXT','text'),column('same','TEXT','text')])],['booleans',table('booleans',[column('true'),column('false')])],['quoted',table('quoted',[column('foo'),column('x')])]])};
const resolve=sql=>expandAndResolveSelect(parseSql(sql).statement,schema);
test('selectExpander preserves ordered duplicate names, wildcard visibility, and direct metadata',()=>{
 const r=resolve('SELECT *, b.*, a.x AS x, a.rowid FROM a JOIN b USING(x)');
 assert.deepEqual(r.result.map(x=>x.name),['x','same','y','same','x','y','same','x','rowid']);
 assert.deepEqual(r.result.map(x=>x.source?.table.name??null),['a','a','b','b','b','b','b','a','a']);
 assert.deepEqual(r.result[0].descriptor,{name:'x',declaredType:'INTEGER',database:'main',table:'a',origin:'x',affinity:'integer',collation:'BINARY'});
 assert.equal(r.result[7].descriptor.declaredType,'INTEGER');
 assert.equal(r.result[8].columnIndex,-1);
 assert.ok(Object.isFrozen(r)&&Object.isFrozen(r.sources)&&Object.isFrozen(r.result));
});
test('lookupName applies aliases, qualification, ambiguity, no-such-column, and rowid shadowing',()=>{
 assert.throws(()=>resolve('SELECT x FROM a INDEXED BY nope'),e=>e instanceof NameResolutionError&&e.message==='no such index: nope');
 assert.doesNotThrow(()=>resolve('SELECT x FROM a NOT INDEXED'));
 assert.equal(resolve('SELECT main.a.rowid FROM main.a').result[0].columnIndex,-1);
 assert.throws(()=>resolve('SELECT main.a.x FROM main.a AS aa'),e=>e instanceof NameResolutionError&&e.message==='no such column: main.a.x');
 assert.equal(resolve('SELECT main.a.x FROM main.a').result[0].source.table.name,'a');
 assert.throws(()=>resolve('SELECT x FROM temp.a'),e=>e instanceof NameResolutionError&&e.message==='no such table: temp.a');
 const collated=resolve('SELECT a.x COLLATE nocase AS c FROM a').result[0];assert.equal(collated.source.table.name,'a');assert.equal(collated.descriptor.collation,'nocase');
 assert.throws(()=>resolve('SELECT missing COLLATE absent FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b WHERE missing COLLATE absent'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON missing COLLATE absent=b.x'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x COLLATE missing FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such collation sequence: missing');
 assert.equal(resolve('SELECT (a.x COLLATE nocase) FROM a').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT (a.x) FROM a').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT ((main.a.x)) FROM a').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT main.a.x FROM a').result[0].source.table.name,'a');
 assert.throws(()=>resolve('SELECT temp.a.x FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: temp.a.x');
 assert.throws(()=>resolve('SELECT main.aa.x FROM a AS aa'),e=>e instanceof NameResolutionError&&e.message==='no such column: main.aa.x');
 assert.equal(resolve('SELECT aa.x FROM a aa').result[0].source.alias,'aa');
 assert.throws(()=>resolve('SELECT a.x FROM a aa'),e=>e instanceof NameResolutionError&&e.message==='no such column: a.x');
 assert.doesNotThrow(()=>resolve('SELECT a.x AS z,a.x+1 AS z FROM a JOIN b WHERE z>0'));
 assert.doesNotThrow(()=>resolve('SELECT a.x AS z,a.x+1 AS z FROM a JOIN b ON z=b.x'));
 assert.doesNotThrow(()=>resolve('SELECT a.x AS z,a.x+1 AS z FROM a JOIN b ON 1 GROUP BY z'));
 assert.throws(()=>resolve('SELECT a.x AS same FROM a JOIN b WHERE same>0'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: same');
 assert.doesNotThrow(()=>resolve('SELECT a.x AS chosen FROM a JOIN b WHERE chosen>0'));
 assert.throws(()=>resolve('SELECT abs(missing,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT count(missing,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT string_agg(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function string_agg()');
 assert.doesNotThrow(()=>resolve('SELECT string_agg(x,x), group_concat(x), group_concat(x,x), count(), count(x), sum(x), total(x), avg(x), min(x), max(x), min(x,x), max(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT group_concat(x,x,x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function group_concat()');
 assert.throws(()=>resolve('SELECT count(x,x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function count()');
 assert.throws(()=>resolve('SELECT min() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function min()');
 assert.throws(()=>resolve('SELECT avg(x,x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function avg()');
 assert.throws(()=>resolve('SELECT sum() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sum()');
 assert.doesNotThrow(()=>resolve('SELECT sqlite_source_id(), sqlite_log(x,x), unistr(x), unistr_quote(x), substring(x,x), substring(x,x,x) FROM a'));
 assert.throws(()=>resolve('SELECT sqlite_source_id(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sqlite_source_id()');
 assert.throws(()=>resolve('SELECT sqlite_log(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sqlite_log()');
 assert.throws(()=>resolve('SELECT substring(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function substring()');
 assert.doesNotThrow(()=>resolve('SELECT sqlite_offset(x) FROM a'));
 assert.throws(()=>resolve('SELECT sqlite_offset() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sqlite_offset()');
 assert.throws(()=>resolve('SELECT json_group_array(x) FILTER (WHERE x) OVER () FROM a WHERE json_group_array(x) FILTER (WHERE x) OVER ()'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function json_group_array()');
 assert.throws(()=>resolve('SELECT x FROM a HAVING json_group_array(x) FILTER (WHERE x) OVER ()'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.doesNotThrow(()=>resolve('SELECT json_group_array(x) FILTER (WHERE x) OVER () AS j FROM a ORDER BY j'));
 assert.doesNotThrow(()=>resolve('SELECT json_group_array(x) FILTER (WHERE x) OVER () FROM a ORDER BY json_group_array(x) FILTER (WHERE x) OVER ()'));
 assert.throws(()=>resolve('SELECT json_group_array(x) FILTER (WHERE x) OVER () AS j FROM a GROUP BY +j COLLATE binary'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function j');
 assert.throws(()=>resolve('SELECT json_group_array(x) FILTER (WHERE x) OVER () FROM a GROUP BY 1'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function json_group_array()');
 assert.throws(()=>resolve('SELECT json_group_array(x) FILTER (WHERE x) OVER () AS j FROM a GROUP BY j'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function j');
 assert.throws(()=>resolve('SELECT percentile(x,50) OVER () AS p FROM a GROUP BY +p'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: percentile()');
 assert.throws(()=>resolve('SELECT percentile(x,50) OVER () AS p FROM a GROUP BY +p COLLATE binary'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function p');
 assert.throws(()=>resolve('SELECT percentile(x,50) OVER () AS p FROM a GROUP BY (p) COLLATE binary'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function p');
 assert.throws(()=>resolve('SELECT percentile(x,50) OVER () AS p FROM a GROUP BY p COLLATE binary'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function p');
 assert.throws(()=>resolve('SELECT percentile(x,50) OVER () AS p FROM a GROUP BY p'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function p');
 assert.throws(()=>resolve('SELECT percentile(x,50) OVER () FROM a GROUP BY percentile(x,50) OVER ()'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function percentile()');
 assert.doesNotThrow(()=>resolve('SELECT median(x) OVER () AS z FROM a ORDER BY z COLLATE binary'));
 assert.doesNotThrow(()=>resolve('SELECT median(x) OVER () AS z FROM a ORDER BY z'));
 assert.doesNotThrow(()=>resolve('SELECT median(x) OVER () FROM a ORDER BY median(x) OVER ()'));
 assert.doesNotThrow(()=>resolve('SELECT median(x) OVER (), percentile(x,x) OVER (), percentile_cont(x,x) OVER (), percentile_disc(x,x) OVER (), json_group_array(x) OVER (), jsonb_group_array(x) OVER (), json_group_object(x,x) OVER (), jsonb_group_object(x,x) OVER () FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT median(x), percentile(x,x), percentile_cont(x,x), percentile_disc(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT median(x,x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function median()');
 assert.throws(()=>resolve('SELECT percentile(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function percentile()');
 assert.throws(()=>resolve('SELECT median(x) FROM a WHERE median(x)>0'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function median()');
 assert.doesNotThrow(()=>resolve('SELECT ceil(x), ceiling(x), floor(x), trunc(x), ln(x), log(x), log(x,x), log10(x), log2(x), exp(x), pow(x,x), power(x,x), mod(x,x), acos(x), asin(x), atan(x), atan2(x,x), cos(x), sin(x), tan(x), cosh(x), sinh(x), tanh(x), acosh(x), asinh(x), atanh(x), sqrt(x), radians(x), degrees(x), pi() FROM a'));
 assert.throws(()=>resolve('SELECT pi(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function pi()');
 assert.throws(()=>resolve('SELECT pow(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function pow()');
 assert.doesNotThrow(()=>resolve('SELECT sqlite_compileoption_used(x), sqlite_compileoption_get(x), sign(x) FROM a'));
 assert.throws(()=>resolve('SELECT sign() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sign()');
 assert.throws(()=>resolve('SELECT sqlite_compileoption_get() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sqlite_compileoption_get()');
 assert.doesNotThrow(()=>resolve('SELECT json_group_array(x), jsonb_group_array(x), json_group_object(x,x), jsonb_group_object(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT json_group_array(x,x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function json_group_array()');
 assert.throws(()=>resolve('SELECT json_group_object(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function json_group_object()');
 assert.throws(()=>resolve('SELECT json_group_array(x) FROM a WHERE json_group_array(x)>0'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function json_group_array()');
 assert.doesNotThrow(()=>resolve('SELECT json_array_insert(x), json_array_insert(x,x,x), jsonb_array_insert(x,x,x), json_parse(x) FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT json_extract(x), json_extract(x,x), jsonb_extract(x,x), json_insert(x), json_insert(x,x,x), jsonb_insert(x,x,x), json_object(), json_object(x,x), jsonb_object(x,x), json_remove(x), json_remove(x,x), jsonb_remove(x,x), json_replace(x), json_replace(x,x,x), jsonb_replace(x,x,x), json_set(x), json_set(x,x,x), jsonb_set(x,x,x) FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT json(x), jsonb(x), json_array(), json_array(x,x), jsonb_array(x), json_array_length(x), json_array_length(x,x), json_error_position(x), json_patch(x,x), jsonb_patch(x,x), json_pretty(x), json_pretty(x,x), json_quote(x), json_type(x), json_type(x,x), json_valid(x), json_valid(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT json() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function json()');
 assert.throws(()=>resolve('SELECT json_patch(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function json_patch()');
 assert.doesNotThrow(()=>resolve('SELECT like(x,x), like(x,x,x), glob(x,x), load_extension(x), load_extension(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT like(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function like()');
 assert.throws(()=>resolve('SELECT glob(x,x,x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function glob()');
 assert.throws(()=>resolve('SELECT load_extension() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function load_extension()');
 assert.doesNotThrow(()=>resolve('SELECT date(), date(x,x), time(x), datetime(x), julianday(x), unixepoch(x), strftime(x), strftime(x,x), timediff(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT timediff(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function timediff()');
 assert.doesNotThrow(()=>resolve('SELECT iif(x,1), iif(x,1,0), iif(x,1,x,2,0), if(x,1,0) FROM a'));
 assert.throws(()=>resolve('SELECT iif(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function iif()');
 assert.doesNotThrow(()=>resolve('SELECT subtype(x), round(x), round(x,x), concat(), concat(x,x), concat_ws(x), concat_ws(x,x), ifnull(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT round() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function round()');
 assert.throws(()=>resolve('SELECT concat_ws() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function concat_ws()');
 assert.throws(()=>resolve('SELECT ifnull(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function ifnull()');
 assert.doesNotThrow(()=>resolve('SELECT ltrim(x), ltrim(x,x), rtrim(x), trim(x,x), instr(x,x), printf(x), format(x,x), unhex(x), unhex(x,x) FROM a'));
 assert.throws(()=>resolve('SELECT trim() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function trim()');
 assert.throws(()=>resolve('SELECT instr(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function instr()');
 assert.doesNotThrow(()=>resolve('SELECT quote(x), zeroblob(x), randomblob(x), random(), sqlite_version(), changes(), total_changes(), last_insert_rowid() FROM a'));
 assert.throws(()=>resolve('SELECT random(x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function random()');
 assert.throws(()=>resolve('SELECT quote() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function quote()');
 assert.doesNotThrow(()=>resolve('SELECT lower(x), upper(x) FROM a'));
 assert.throws(()=>resolve('SELECT lower() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function lower()');
 assert.throws(()=>resolve('SELECT upper(x,x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function upper()');
 assert.throws(()=>resolve('SELECT abs(a.x,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function abs()');
 assert.throws(()=>resolve('SELECT row_number() OVER () FROM a GROUP BY 1'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function row_number()');
 assert.throws(()=>resolve('SELECT row_number() OVER () FROM a GROUP BY +1'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function row_number()');
 assert.doesNotThrow(()=>resolve('SELECT row_number() OVER () FROM a ORDER BY 1'));
 assert.throws(()=>resolve('SELECT row_number() OVER () AS r FROM a WHERE r'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function r');
 assert.throws(()=>resolve('SELECT row_number() OVER () AS r FROM a GROUP BY r'),e=>e instanceof NameResolutionError&&e.message==='misuse of aliased window function r');
 assert.throws(()=>resolve('SELECT a.x AS y,sum(a.x) OVER (PARTITION BY y) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: y');
 assert.throws(()=>resolve('SELECT a.x FROM a WHERE row_number() OVER ()'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function row_number()');
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY row_number() OVER ()'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function row_number()');
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a ORDER BY row_number() OVER ()'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER missing FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such window: missing');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (ORDER BY missing),w AS (ORDER BY a.x)'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (ORDER BY a.x),w AS (ORDER BY missing)'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (missing ORDER BY a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such window: missing');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (w ORDER BY a.x) FROM a WINDOW w AS (ORDER BY a.x)'),e=>e instanceof NameResolutionError&&e.message==='cannot override ORDER BY clause of window: w');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (w PARTITION BY a.x) FROM a WINDOW w AS (PARTITION BY a.x)'),e=>e instanceof NameResolutionError&&e.message==='cannot override PARTITION clause of window: w');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (w ROWS CURRENT ROW) FROM a WINDOW w AS (ROWS CURRENT ROW)'),e=>e instanceof NameResolutionError&&e.message==='cannot override frame specification of window: w');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER (w ORDER BY a.x) FROM a WINDOW w AS (PARTITION BY a.x)'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (RANGE 1 PRECEDING)'),e=>e instanceof NameResolutionError&&e.message==='RANGE with offset PRECEDING/FOLLOWING requires one ORDER BY expression');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (ORDER BY a.x,a.x RANGE 1 PRECEDING)'),e=>e instanceof NameResolutionError&&e.message==='RANGE with offset PRECEDING/FOLLOWING requires one ORDER BY expression');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (ORDER BY a.x RANGE 1 PRECEDING)'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (ROWS BETWEEN CURRENT ROW AND 1 PRECEDING)'),e=>e instanceof NameResolutionError&&e.message==='unsupported frame specification');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER w2 FROM a WINDOW w1 AS (ORDER BY a.x),w1 AS (PARTITION BY a.x),w2 AS (w1 ORDER BY a.x)'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w2 FROM a WINDOW w1 AS (PARTITION BY a.x),w1 AS (ORDER BY a.x),w2 AS (w1 ORDER BY a.x)'),e=>e instanceof NameResolutionError&&e.message==='cannot override ORDER BY clause of window: w1');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w2 FROM a WINDOW w1 AS (ROWS CURRENT ROW),w2 AS (w1)'),e=>e instanceof NameResolutionError&&e.message==='cannot override frame specification of window: w1');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER w2 FROM a WINDOW w1 AS (ORDER BY a.x),w2 AS (w1 ROWS CURRENT ROW)'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w2 FROM a WINDOW w1 AS (ORDER BY a.x),w2 AS (w1 ORDER BY a.x)'),e=>e instanceof NameResolutionError&&e.message==='cannot override ORDER BY clause of window: w1');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w2 FROM a WINDOW w1 AS (PARTITION BY a.x),w2 AS (w1 PARTITION BY a.x)'),e=>e instanceof NameResolutionError&&e.message==='cannot override PARTITION clause of window: w1');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER w2 FROM a WINDOW w1 AS (PARTITION BY a.x),w2 AS (w1 ORDER BY a.x)'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (PARTITION BY missing)'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (ORDER BY missing)'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER w FROM a WINDOW w AS (PARTITION BY a.x)'));
 assert.doesNotThrow(()=>resolve('SELECT row_number() OVER (),sum(a.x) OVER () FROM a'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ROWS BETWEEN CURRENT ROW AND 1 PRECEDING) FROM a'),e=>e instanceof NameResolutionError&&e.message==='unsupported frame specification');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ROWS BETWEEN 1 FOLLOWING AND CURRENT ROW) FROM a'),e=>e instanceof NameResolutionError&&e.message==='unsupported frame specification');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ROWS BETWEEN 1 FOLLOWING AND 1 PRECEDING) FROM a'),e=>e instanceof NameResolutionError&&e.message==='unsupported frame specification');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER (ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) FROM a'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (RANGE 1 PRECEDING) FROM a'),e=>e instanceof NameResolutionError&&e.message==='RANGE with offset PRECEDING/FOLLOWING requires one ORDER BY expression');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ORDER BY a.x,a.x RANGE 1 PRECEDING) FROM a'),e=>e instanceof NameResolutionError&&e.message==='RANGE with offset PRECEDING/FOLLOWING requires one ORDER BY expression');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER (ORDER BY a.x RANGE 1 PRECEDING) FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER (RANGE CURRENT ROW) FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER (ROWS missing PRECEDING) FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER (ROWS BETWEEN missing PRECEDING AND CURRENT ROW) FROM a'));
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (PARTITION BY missing) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ORDER BY missing) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT sum(DISTINCT missing) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='DISTINCT is not supported for window functions');
 assert.throws(()=>resolve('SELECT lag(DISTINCT missing) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='DISTINCT is not supported for window functions');
 assert.throws(()=>resolve('SELECT row_number(1) FILTER (WHERE a.x) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function row_number()');
 assert.throws(()=>resolve('SELECT lag() FILTER (WHERE missing) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function lag()');
 assert.throws(()=>resolve('SELECT lag(missing) FILTER (WHERE a.x) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='FILTER clause may only be used with aggregate window functions');
 assert.throws(()=>resolve('SELECT row_number() FILTER (WHERE missing) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT row_number() FILTER (WHERE a.x) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='FILTER clause may only be used with aggregate window functions');
 assert.throws(()=>resolve('SELECT lag(a.x) FILTER (WHERE a.x) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='FILTER clause may only be used with aggregate window functions');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ORDER BY a.x ROWS BETWEEN CURRENT ROW AND 1 PRECEDING) FROM a'),e=>e instanceof NameResolutionError&&e.message==='unsupported frame specification');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ORDER BY a.x ROWS BETWEEN 1 FOLLOWING AND CURRENT ROW) FROM a'),e=>e instanceof NameResolutionError&&e.message==='unsupported frame specification');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER (ORDER BY a.x ROWS BETWEEN 1 FOLLOWING AND 1 PRECEDING) FROM a'),e=>e instanceof NameResolutionError&&e.message==='unsupported frame specification');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) OVER (ORDER BY a.x ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) FILTER (WHERE a.x) OVER () FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT rank() OVER (),dense_rank() OVER (),percent_rank() OVER (),cume_dist() OVER (),ntile(2) OVER (),lag(a.x) OVER (),lead(a.x,1,0) OVER (),first_value(a.x) OVER (),last_value(a.x) OVER (),nth_value(a.x,1) OVER () FROM a'));
 assert.throws(()=>resolve('SELECT rank(1) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function rank()');
 assert.throws(()=>resolve('SELECT abs(a.x) OVER (ORDER BY missing) FROM a'),e=>e instanceof NameResolutionError&&e.message==='abs() may not be used as a window function');
 assert.throws(()=>resolve('SELECT abs(a.x) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='abs() may not be used as a window function');
 assert.throws(()=>resolve('SELECT sum(missing) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.doesNotThrow(()=>resolve('SELECT char(),char(a.x,65) FROM a'));
 assert.throws(()=>resolve('SELECT char(missing) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT mystery(a.x) FILTER (WHERE missing) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such function: mystery');
 assert.throws(()=>resolve('SELECT mystery(missing) FILTER (WHERE a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT mystery(a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such function: mystery');
 assert.throws(()=>resolve('SELECT mystery(missing) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) FILTER (WHERE a.x) FROM a HAVING 1'));
 assert.doesNotThrow(()=>resolve('SELECT json_group_array(a.x) FILTER (WHERE a.x) FROM a HAVING 1'));
 assert.doesNotThrow(()=>resolve('SELECT percentile(a.x,50) FILTER (WHERE a.x) FROM a HAVING 1'));
 assert.throws(()=>resolve('SELECT json_group_array(DISTINCT x,x) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='DISTINCT is not supported for window functions');
 assert.throws(()=>resolve('SELECT percentile(DISTINCT x) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='DISTINCT is not supported for window functions');
 assert.throws(()=>resolve('SELECT sum(sum(x)) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function sum()');
 assert.throws(()=>resolve('SELECT json_group_array(median(x)) OVER () FROM a'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function median()');
 assert.throws(()=>resolve('SELECT sum(a.x) OVER () FROM a HAVING 1'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.throws(()=>resolve('SELECT json_group_array(a.x) OVER () FROM a HAVING 1'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.throws(()=>resolve('SELECT percentile(a.x,50) OVER () FROM a HAVING 1'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.throws(()=>resolve('SELECT json_group_array(json_group_object(x,x)) FROM a'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function json_group_object()');
 assert.throws(()=>resolve('SELECT percentile(median(x),x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function median()');
 assert.throws(()=>resolve('SELECT json_group_array(x) FILTER (WHERE median(x)) FROM a'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function median()');
 assert.throws(()=>resolve('SELECT sum(sum(a.x)) FROM a'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function sum()');
 assert.doesNotThrow(()=>resolve('SELECT abs(sum(a.x)),max(sum(a.x),a.x),sum(abs(a.x)) FROM a'));
 assert.throws(()=>resolve('SELECT abs(a.x) FILTER (WHERE a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='FILTER may not be used with non-aggregate abs()');
 assert.throws(()=>resolve('SELECT min(a.x,a.x) FILTER (WHERE a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='FILTER may not be used with non-aggregate min()');
 assert.throws(()=>resolve('SELECT sum(a.x) FILTER (WHERE count(a.x)) FROM a'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function count()');
 assert.throws(()=>resolve('SELECT sum(a.x) FILTER (WHERE missing) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT sum(*) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sum()');
 assert.throws(()=>resolve('SELECT abs(*) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function abs()');
 assert.throws(()=>resolve('SELECT min(*) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function min()');
 assert.throws(()=>resolve('SELECT min() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function min()');
 assert.throws(()=>resolve('SELECT max() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function max()');
 assert.doesNotThrow(()=>resolve('SELECT min(a.x,a.x),max(a.x,a.x,a.x) FROM a'));
 assert.throws(()=>resolve('SELECT count(a.x,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function count()');
 assert.throws(()=>resolve('SELECT sum() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sum()');
 assert.throws(()=>resolve('SELECT sum(a.x,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function sum()');
 assert.doesNotThrow(()=>resolve('SELECT min(DISTINCT a.x,a.x),coalesce(DISTINCT a.x,a.x) FROM a'));
 assert.throws(()=>resolve('SELECT group_concat(DISTINCT a.x,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='DISTINCT aggregates must have exactly one argument');
 assert.throws(()=>resolve('SELECT group_concat(a.x,a.x,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function group_concat()');
 assert.throws(()=>resolve('SELECT a.x FROM a WHERE sum(a.x)>0'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function sum()');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON count(*)>0'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function count()');
 assert.throws(()=>resolve('SELECT sum(a.x) AS z FROM a WHERE z'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT abs(sum(a.x)) AS z FROM a WHERE z+0'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT sum(a.x) AS z FROM a JOIN b ON z'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT a.x FROM a LIMIT row_number() OVER ()'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function row_number()');
 assert.throws(()=>resolve('SELECT a.x FROM a LIMIT sum(1) OVER ()'),e=>e instanceof NameResolutionError&&e.message==='misuse of window function sum()');
 assert.throws(()=>resolve('SELECT a.x FROM a LIMIT sum(1)'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function sum()');
 assert.throws(()=>resolve('SELECT a.x FROM a LIMIT count(*)'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate function count()');
 assert.throws(()=>resolve('SELECT a.x AS z FROM a LIMIT z'),e=>e instanceof NameResolutionError&&e.message==='no such column: z');
 assert.throws(()=>resolve('SELECT a.x FROM a LIMIT abs(missing)'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a LIMIT 1 OFFSET missing'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a ORDER BY sum(a.x)'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.doesNotThrow(()=>resolve('SELECT sum(a.x) FROM a ORDER BY sum(a.x)'));
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a GROUP BY a.x ORDER BY sum(a.x)'));
 assert.doesNotThrow(()=>resolve('SELECT a.x!=1 FROM a UNION ALL SELECT a.x FROM a ORDER BY x<>1'));
 assert.doesNotThrow(()=>resolve('SELECT a.x==1 FROM a UNION ALL SELECT a.x FROM a ORDER BY x=1'));
 assert.throws(()=>resolve('SELECT [true] FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: true');
 assert.throws(()=>resolve('SELECT `false` FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: false');
 assert.doesNotThrow(()=>resolve('SELECT "true" FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT "foo", +"foo", "foo"||x FROM a'));
 const quotedColumn=resolve('SELECT "foo" FROM quoted');
 assert.equal(quotedColumn.result[0].source.table.name,'quoted');
 assert.throws(()=>resolve('SELECT a."foo" FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: a.foo');
 assert.throws(()=>resolve('SELECT ? FROM a UNION ALL SELECT x FROM a ORDER BY ?'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.throws(()=>resolve('SELECT x FROM a UNION ALL SELECT x FROM a ORDER BY x COLLATE bogus'),e=>e instanceof NameResolutionError&&e.message==='no such collation sequence: bogus');
 assert.doesNotThrow(()=>resolve('SELECT x FROM a UNION ALL SELECT x FROM a ORDER BY x COLLATE nocase'));
 assert.doesNotThrow(()=>resolve('SELECT ?1 FROM a UNION ALL SELECT x FROM a ORDER BY ?1'));
 assert.throws(()=>resolve('SELECT ?1 FROM a UNION ALL SELECT x FROM a ORDER BY ?2'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.doesNotThrow(()=>resolve('SELECT :p FROM a UNION ALL SELECT x FROM a ORDER BY :p'));
 assert.throws(()=>resolve('SELECT :p FROM a UNION ALL SELECT x FROM a ORDER BY @p'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.doesNotThrow(()=>resolve('SELECT ?, ?1, :p, @p, $p FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT 123, 0x10, current_date, CURRENT_TIME, current_timestamp FROM a'));
 assert.doesNotThrow(()=>resolve("SELECT 1.0, 1e0, NULL, x'AB' FROM a"));
 assert.throws(()=>resolve("SELECT x'AB' FROM a UNION ALL SELECT x FROM a ORDER BY x'ab'"),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.throws(()=>resolve('SELECT 1.0 FROM a UNION ALL SELECT x FROM a ORDER BY 1.00'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.doesNotThrow(()=>resolve('SELECT NULL FROM a UNION ALL SELECT x FROM a ORDER BY null'));
 assert.doesNotThrow(()=>resolve('SELECT TRUE, false FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT \'foo\' FROM a UNION ALL SELECT x FROM a ORDER BY "foo"'));
 assert.doesNotThrow(()=>resolve('SELECT "foo" FROM a UNION ALL SELECT x FROM a ORDER BY \'foo\''));
 assert.doesNotThrow(()=>resolve('SELECT +"foo" FROM a UNION ALL SELECT x FROM a ORDER BY +\'foo\''));
 assert.doesNotThrow(()=>resolve('SELECT a.x IS TRUE FROM a UNION ALL SELECT a.x FROM a ORDER BY x IS TRUE'));
 assert.throws(()=>resolve('SELECT a.x IS TRUE FROM a UNION ALL SELECT a.x FROM a ORDER BY x IS 1'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 const booleanColumns=resolve('SELECT TRUE, false FROM booleans');
 assert.equal(booleanColumns.result[0].source.table.name,'booleans');
 assert.equal(booleanColumns.result[1].source.table.name,'booleans');
 assert.doesNotThrow(()=>resolve('SELECT a.x IS NOT NULL FROM a UNION ALL SELECT a.x FROM a ORDER BY x NOTNULL'));
 assert.doesNotThrow(()=>resolve('SELECT a.x IS NULL FROM a UNION ALL SELECT a.x FROM a ORDER BY x ISNULL'));
 assert.doesNotThrow(()=>resolve('SELECT a.x+1 FROM a UNION ALL SELECT a.x+2 FROM a ORDER BY x+01'));
 assert.throws(()=>resolve('SELECT a.x+1.0 FROM a UNION ALL SELECT a.x+2 FROM a ORDER BY x+1.00'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.doesNotThrow(()=>resolve('SELECT a.x+1 FROM a UNION ALL SELECT a.x+2 FROM a ORDER BY x+1'));
 assert.doesNotThrow(()=>resolve('SELECT a.x+1 FROM a UNION ALL SELECT a.x+2 FROM a ORDER BY main.a.x+1'));
 assert.throws(()=>resolve('SELECT a.x+1 FROM a UNION ALL SELECT a.x+2 FROM a ORDER BY z.x+1'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.throws(()=>resolve('SELECT likely() FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function likely()');
 assert.throws(()=>resolve('SELECT likely(a.x,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function likely()');
 assert.doesNotThrow(()=>resolve('SELECT likelihood(a.x,1e-999) FROM a'));
 assert.throws(()=>resolve('SELECT likelihood(a.x,1e999) FROM a'),e=>e instanceof NameResolutionError&&e.message==='second argument to likelihood() must be a constant between 0.0 and 1.0');
 assert.doesNotThrow(()=>resolve('SELECT likelihood(a.x,5e-1) FROM a'));
 assert.doesNotThrow(()=>resolve('SELECT likelihood(a.x,((.5))) FROM a'));
 assert.throws(()=>resolve('SELECT likelihood(a.x,5.) FROM a'),e=>e instanceof NameResolutionError&&e.message==='second argument to likelihood() must be a constant between 0.0 and 1.0');
 assert.throws(()=>resolve('SELECT likelihood(a.x,+0.5) FROM a'),e=>e instanceof NameResolutionError&&e.message==='second argument to likelihood() must be a constant between 0.0 and 1.0');
 assert.throws(()=>resolve('SELECT likelihood(a.x,a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='second argument to likelihood() must be a constant between 0.0 and 1.0');
 assert.throws(()=>resolve('SELECT likelihood(a.x,-0.1) FROM a'),e=>e instanceof NameResolutionError&&e.message==='second argument to likelihood() must be a constant between 0.0 and 1.0');
 assert.throws(()=>resolve('SELECT likelihood(a.x,1.1) FROM a'),e=>e instanceof NameResolutionError&&e.message==='second argument to likelihood() must be a constant between 0.0 and 1.0');
 assert.throws(()=>resolve('SELECT likelihood(a.x,1) FROM a'),e=>e instanceof NameResolutionError&&e.message==='second argument to likelihood() must be a constant between 0.0 and 1.0');
 assert.doesNotThrow(()=>resolve('SELECT likelihood(a.x,(0.5)) FROM a'));
 assert.throws(()=>resolve('SELECT likelihood(a.x) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function likelihood()');
 assert.throws(()=>resolve('SELECT likelihood(a.x,0.5,1) FROM a'),e=>e instanceof NameResolutionError&&e.message==='wrong number of arguments to function likelihood()');
 assert.throws(()=>resolve('SELECT likelihood(missing,0.5,1) FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.doesNotThrow(()=>resolve('SELECT likely(a.x) FROM a UNION ALL SELECT a.x FROM a ORDER BY x'));
 assert.doesNotThrow(()=>resolve('SELECT unlikely(a.x) FROM a UNION ALL SELECT a.x FROM a ORDER BY x'));
 assert.doesNotThrow(()=>resolve('SELECT likelihood(a.x,0.5) FROM a UNION ALL SELECT a.x FROM a ORDER BY x'));
 assert.throws(()=>resolve('SELECT a.x FROM a UNION ALL SELECT a.x FROM a ORDER BY likely(x)'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a UNION ALL SELECT a.x FROM a ORDER BY x COLLATE binary COLLATE nocase'));
 assert.doesNotThrow(()=>resolve('SELECT a.x COLLATE binary COLLATE nocase FROM a UNION ALL SELECT a.x FROM a ORDER BY x'));
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a UNION ALL SELECT a.x FROM a ORDER BY a.x COLLATE nocase'));
 assert.doesNotThrow(()=>resolve('SELECT a.x AS y FROM a UNION ALL SELECT a.x FROM a ORDER BY y COLLATE nocase'));
 assert.doesNotThrow(()=>resolve('SELECT a.x+1 FROM a UNION ALL SELECT a.x+2 FROM a ORDER BY (a.x+1)'));
 assert.throws(()=>resolve('SELECT a.x+1 FROM a UNION ALL SELECT a.x+2 FROM a ORDER BY +a.x+1'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a UNION ALL SELECT a.x AS y FROM a ORDER BY y'));
 assert.throws(()=>resolve('SELECT a.x FROM a UNION ALL SELECT a.x FROM a ORDER BY missing'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.throws(()=>resolve('SELECT a.x FROM a UNION ALL SELECT a.x FROM a ORDER BY a.x+1'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term does not match any column in the result set');
 assert.throws(()=>resolve('SELECT a.x FROM a ORDER BY missing'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a ORDER BY 2'),e=>e instanceof NameResolutionError&&e.message==='1st ORDER BY term out of range - should be between 1 and 1');
 assert.doesNotThrow(()=>resolve('SELECT a.x AS z FROM a ORDER BY z'));
 assert.throws(()=>resolve('SELECT a.x FROM a HAVING missing'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.throws(()=>resolve('SELECT a.x FROM a HAVING count(*)>0'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.throws(()=>resolve('SELECT min(a.x,b.y) FROM a JOIN b HAVING missing'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.throws(()=>resolve('SELECT max(a.x,b.y) FROM a JOIN b HAVING missing'),e=>e instanceof NameResolutionError&&e.message==='HAVING clause on a non-aggregate query');
 assert.throws(()=>resolve('SELECT min(a.x) FROM a HAVING missing'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT count(*) FROM a HAVING missing'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON onbad=1 WHERE wbad=1 GROUP BY gbad HAVING hbad'),e=>e instanceof NameResolutionError&&e.message==='no such column: hbad');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON onbad=1 WHERE wbad=1 GROUP BY gbad'),e=>e instanceof NameResolutionError&&e.message==='no such column: wbad');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON onbad=1 GROUP BY gbad'),e=>e instanceof NameResolutionError&&e.message==='no such column: onbad');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON 1 GROUP BY gbad'),e=>e instanceof NameResolutionError&&e.message==='no such column: gbad');
 assert.throws(()=>resolve('SELECT sum(a.x) AS z FROM a GROUP BY z+0'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT abs(sum(a.x)) AS z FROM a GROUP BY 1+z'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT sum(a.x) AS z FROM a GROUP BY +z'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT sum(a.x) AS z FROM a GROUP BY z COLLATE nocase'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT abs(sum(a.x)) AS z FROM a GROUP BY (z COLLATE binary)'),e=>e instanceof NameResolutionError&&e.message==='misuse of aggregate: sum()');
 assert.throws(()=>resolve('SELECT sum(a.x) AS z FROM a GROUP BY (z)'),e=>e instanceof NameResolutionError&&e.message==='aggregate functions are not allowed in the GROUP BY clause');
 assert.throws(()=>resolve('SELECT sum(a.x) AS z FROM a GROUP BY z'),e=>e instanceof NameResolutionError&&e.message==='aggregate functions are not allowed in the GROUP BY clause');
 assert.throws(()=>resolve('SELECT abs(sum(a.x)) AS z FROM a GROUP BY z'),e=>e instanceof NameResolutionError&&e.message==='aggregate functions are not allowed in the GROUP BY clause');
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY sum(a.x)'),e=>e instanceof NameResolutionError&&e.message==='aggregate functions are not allowed in the GROUP BY clause');
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY abs(sum(a.x))'),e=>e instanceof NameResolutionError&&e.message==='aggregate functions are not allowed in the GROUP BY clause');
 assert.throws(()=>resolve('SELECT count(*) FROM a GROUP BY 1'),e=>e instanceof NameResolutionError&&e.message==='aggregate functions are not allowed in the GROUP BY clause');
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY 0'),e=>e instanceof NameResolutionError&&e.message==='1st GROUP BY term out of range - should be between 1 and 1');
 assert.throws(()=>resolve('SELECT a.x,a.x+1 FROM a GROUP BY 3'),e=>e instanceof NameResolutionError&&e.message==='1st GROUP BY term out of range - should be between 1 and 2');
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY (2)'),e=>e instanceof NameResolutionError&&e.message==='1st GROUP BY term out of range - should be between 1 and 1');
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY 2 COLLATE nocase'),e=>e instanceof NameResolutionError&&e.message==='1st GROUP BY term out of range - should be between 1 and 1');
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY +2'),e=>e instanceof NameResolutionError&&e.message==='1st GROUP BY term out of range - should be between 1 and 1');
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a GROUP BY 2147483648'));
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a GROUP BY -2147483648'));
 assert.throws(()=>resolve('SELECT a.x FROM a GROUP BY -1'),e=>e instanceof NameResolutionError&&e.message==='1st GROUP BY term out of range - should be between 1 and 1');
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a GROUP BY 1'));
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b WHERE missing+1'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b WHERE rowid>0'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: rowid');
 assert.throws(()=>resolve('SELECT missing+1 FROM a JOIN b'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT outmissing FROM a JOIN b ON onmissing=1'),e=>e instanceof NameResolutionError&&e.message==='no such column: outmissing');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON onmissing=1 WHERE wheremissing=1'),e=>e instanceof NameResolutionError&&e.message==='no such column: wheremissing');
 assert.throws(()=>resolve('SELECT a.x+x FROM a JOIN b'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: x');
 assert.throws(()=>resolve('SELECT same FROM a JOIN b ON 1'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: same');
 assert.throws(()=>resolve('SELECT nope FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: nope');
 const shadowSchema={tables:new Map([['a',table('a',[column('rowid','TEXT','text')])]])};
 assert.equal(expandAndResolveSelect(parseSql('SELECT rowid,_rowid_ FROM a').statement,shadowSchema).result[0].columnIndex,0);
 assert.equal(expandAndResolveSelect(parseSql('SELECT rowid,_rowid_ FROM a').statement,shadowSchema).result[1].columnIndex,-1);
 assert.equal(expandAndResolveSelect(parseSql('SELECT rowid FROM a JOIN b ON 1').statement,{tables:new Map([['a',table('a',[column('v')])],['b',table('b',[column('rowid','TEXT','text')])]])}).result[0].source.table.name,'b');
});
test('NATURAL and USING synthesize merged visibility and validate both sides',()=>{
 const natural=resolve('SELECT * FROM a NATURAL JOIN b');
 assert.deepEqual(natural.sources[1].using,['x','same']);
 assert.deepEqual(natural.result.map(x=>x.name),['x','same','y']);
 assert.equal(resolve('SELECT x FROM a JOIN b USING(x)').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT x FROM a RIGHT JOIN b USING(x)').result[0].source.table.name,'b');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON a.x COLLATE missing=b.x'),e=>e instanceof NameResolutionError&&e.message==='no such collation sequence: missing');
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a JOIN b ON a.x COLLATE nocase=b.x'));
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a JOIN b ON main.a.x=b.x'));
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON temp.a.x=b.x'),e=>e instanceof NameResolutionError&&e.message==='no such column: temp.a.x');
 assert.throws(()=>resolve('SELECT a.x AS same FROM a JOIN b ON same=b.x'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: same');
 assert.doesNotThrow(()=>resolve('SELECT a.x AS chosen FROM a JOIN b ON chosen=b.x'));
 assert.throws(()=>resolve('SELECT a.x AS chosen FROM a JOIN b ON missing=b.x'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a LEFT JOIN b ON b.x=c.x JOIN b AS c ON 1'),e=>e instanceof NameResolutionError&&e.message==='ON clause references tables to its right');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON b.x=missing JOIN b AS c ON 1'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 const full=resolve('SELECT x FROM a FULL JOIN b USING(x)').result[0];
 assert.equal(full.resolution,'coalesce');assert.equal(full.source,null);assert.deepEqual(full.descriptor,{name:'x',declaredType:null,database:null,table:null,origin:null,affinity:'integer',collation:'BINARY'});assert.deepEqual(full.mergedSources.map(x=>x.source.table.name),['a','b']);
 assert.throws(()=>resolve('SELECT * FROM a JOIN b USING(nope)'),e=>e instanceof NameResolutionError&&e.message==='cannot join using column nope - column not present in both tables');
 assert.throws(()=>resolve('SELECT * FROM a NATURAL JOIN b USING(x)'),e=>e instanceof NameResolutionError&&e.message==='a NATURAL join may not have an ON or USING clause');
});

test('INTEGER PRIMARY KEY resolves to rowid storage while retaining declared metadata',()=>{
 const ipk=column('id','INTEGER','integer');const t=table('ipk',[ipk,column('v','TEXT','text')],[0]);const local={tables:new Map([['ipk',t]])};const r=expandAndResolveSelect(parseSql('SELECT id FROM ipk').statement,local).result[0];assert.equal(r.columnIndex,-1);assert.deepEqual(r.descriptor,{name:'id',declaredType:'INTEGER',database:'main',table:'ipk',origin:'id',affinity:'integer',collation:'BINARY'});
 const aliased=expandAndResolveSelect(parseSql('SELECT id AS renamed FROM ipk').statement,local).result[0];assert.equal(aliased.columnIndex,-1);assert.equal(aliased.descriptor.name,'renamed');assert.equal(aliased.descriptor.origin,'id');assert.equal(aliased.descriptor.declaredType,'INTEGER');
});
