import assert from 'node:assert/strict';
import test from 'node:test';
import {parseSql} from '../../src/internal/parse.ts';
import {expandAndResolveSelect,NameResolutionError} from '../../src/internal/resolve.ts';
const column=(name,declaredType=null,affinity='blob',collation=null)=>Object.freeze({name,declaredType,affinity,collation});
const table=(name,columns,primaryKey=[])=>{columns=Object.freeze(columns);return Object.freeze({kind:'table',name,tableName:name,rootPage:2,sql:'',columns,indexes:Object.freeze([]),withoutRowid:false,primaryKey:Object.freeze(primaryKey.map(i=>columns[i])),storageKey:Object.freeze([])})};
const schema={tables:new Map([['a',table('a',[column('x','INTEGER','integer'),column('same','TEXT','text','NOCASE')])],['b',table('b',[column('x','REAL','real'),column('y','TEXT','text'),column('same','TEXT','text')])]])};
const resolve=sql=>expandAndResolveSelect(parseSql(sql).statement,schema);
test('selectExpander preserves ordered duplicate names, wildcard visibility, and direct metadata',()=>{
 const r=resolve('SELECT *, b.*, a.x AS x, a.rowid FROM a JOIN b USING(x)');
 assert.deepEqual(r.result.map(x=>x.name),['x','same','y','same','x','y','same','x','rowid']);
 assert.deepEqual(r.result.map(x=>x.source?.table.name??null),['a','a','b','b','b','b','b','a','a']);
 assert.deepEqual(r.result[0].descriptor,{name:'x',declaredType:'INTEGER',database:'main',table:'a',origin:'x',affinity:'integer',collation:'BINARY'});
 assert.equal(r.result[7].descriptor.declaredType,'INTEGER');
 assert.equal(r.result[8].columnIndex,-1);
 assert.ok(Object.isFrozen(r)&&Object.isFrozen(r.sources)&&Object.isFrozen(r.result));
});
test('lookupName applies aliases, qualification, ambiguity, no-such-column, and rowid shadowing',()=>{
 assert.throws(()=>resolve('SELECT x FROM a INDEXED BY nope'),e=>e instanceof NameResolutionError&&e.message==='no such index: nope');
 assert.doesNotThrow(()=>resolve('SELECT x FROM a NOT INDEXED'));
 assert.equal(resolve('SELECT main.a.rowid FROM main.a').result[0].columnIndex,-1);
 assert.throws(()=>resolve('SELECT main.a.x FROM main.a AS aa'),e=>e instanceof NameResolutionError&&e.message==='no such column: main.a.x');
 assert.equal(resolve('SELECT main.a.x FROM main.a').result[0].source.table.name,'a');
 assert.throws(()=>resolve('SELECT x FROM temp.a'),e=>e instanceof NameResolutionError&&e.message==='no such table: temp.a');
 const collated=resolve('SELECT a.x COLLATE nocase AS c FROM a').result[0];assert.equal(collated.source.table.name,'a');assert.equal(collated.descriptor.collation,'nocase');
 assert.throws(()=>resolve('SELECT a.x COLLATE missing FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such collation sequence: missing');
 assert.equal(resolve('SELECT (a.x COLLATE nocase) FROM a').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT (a.x) FROM a').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT ((main.a.x)) FROM a').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT main.a.x FROM a').result[0].source.table.name,'a');
 assert.throws(()=>resolve('SELECT temp.a.x FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: temp.a.x');
 assert.throws(()=>resolve('SELECT main.aa.x FROM a AS aa'),e=>e instanceof NameResolutionError&&e.message==='no such column: main.aa.x');
 assert.equal(resolve('SELECT aa.x FROM a aa').result[0].source.alias,'aa');
 assert.throws(()=>resolve('SELECT a.x FROM a aa'),e=>e instanceof NameResolutionError&&e.message==='no such column: a.x');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b WHERE missing+1'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b WHERE rowid>0'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: rowid');
 assert.throws(()=>resolve('SELECT missing+1 FROM a JOIN b'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x+x FROM a JOIN b'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: x');
 assert.throws(()=>resolve('SELECT same FROM a JOIN b ON 1'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: same');
 assert.throws(()=>resolve('SELECT nope FROM a'),e=>e instanceof NameResolutionError&&e.message==='no such column: nope');
 const shadowSchema={tables:new Map([['a',table('a',[column('rowid','TEXT','text')])]])};
 assert.equal(expandAndResolveSelect(parseSql('SELECT rowid,_rowid_ FROM a').statement,shadowSchema).result[0].columnIndex,0);
 assert.equal(expandAndResolveSelect(parseSql('SELECT rowid,_rowid_ FROM a').statement,shadowSchema).result[1].columnIndex,-1);
 assert.equal(expandAndResolveSelect(parseSql('SELECT rowid FROM a JOIN b ON 1').statement,{tables:new Map([['a',table('a',[column('v')])],['b',table('b',[column('rowid','TEXT','text')])]])}).result[0].source.table.name,'b');
});
test('NATURAL and USING synthesize merged visibility and validate both sides',()=>{
 const natural=resolve('SELECT * FROM a NATURAL JOIN b');
 assert.deepEqual(natural.sources[1].using,['x','same']);
 assert.deepEqual(natural.result.map(x=>x.name),['x','same','y']);
 assert.equal(resolve('SELECT x FROM a JOIN b USING(x)').result[0].source.table.name,'a');
 assert.equal(resolve('SELECT x FROM a RIGHT JOIN b USING(x)').result[0].source.table.name,'b');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON a.x COLLATE missing=b.x'),e=>e instanceof NameResolutionError&&e.message==='no such collation sequence: missing');
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a JOIN b ON a.x COLLATE nocase=b.x'));
 assert.doesNotThrow(()=>resolve('SELECT a.x FROM a JOIN b ON main.a.x=b.x'));
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON temp.a.x=b.x'),e=>e instanceof NameResolutionError&&e.message==='no such column: temp.a.x');
 assert.throws(()=>resolve('SELECT a.x AS z,a.x+1 AS z FROM a JOIN b ON z=b.x'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: z');
 assert.throws(()=>resolve('SELECT a.x AS same FROM a JOIN b ON same=b.x'),e=>e instanceof NameResolutionError&&e.message==='ambiguous column name: same');
 assert.doesNotThrow(()=>resolve('SELECT a.x AS chosen FROM a JOIN b ON chosen=b.x'));
 assert.throws(()=>resolve('SELECT a.x AS chosen FROM a JOIN b ON missing=b.x'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 assert.throws(()=>resolve('SELECT a.x FROM a LEFT JOIN b ON b.x=c.x JOIN b AS c ON 1'),e=>e instanceof NameResolutionError&&e.message==='ON clause references tables to its right');
 assert.throws(()=>resolve('SELECT a.x FROM a JOIN b ON b.x=missing JOIN b AS c ON 1'),e=>e instanceof NameResolutionError&&e.message==='no such column: missing');
 const full=resolve('SELECT x FROM a FULL JOIN b USING(x)').result[0];
 assert.equal(full.resolution,'coalesce');assert.equal(full.source,null);assert.deepEqual(full.descriptor,{name:'x',declaredType:null,database:null,table:null,origin:null,affinity:'integer',collation:'BINARY'});assert.deepEqual(full.mergedSources.map(x=>x.source.table.name),['a','b']);
 assert.throws(()=>resolve('SELECT * FROM a JOIN b USING(nope)'),e=>e instanceof NameResolutionError&&e.message==='cannot join using column nope - column not present in both tables');
 assert.throws(()=>resolve('SELECT * FROM a NATURAL JOIN b USING(x)'),e=>e instanceof NameResolutionError&&e.message==='a NATURAL join may not have an ON or USING clause');
});

test('INTEGER PRIMARY KEY resolves to rowid storage while retaining declared metadata',()=>{
 const ipk=column('id','INTEGER','integer');const t=table('ipk',[ipk,column('v','TEXT','text')],[0]);const local={tables:new Map([['ipk',t]])};const r=expandAndResolveSelect(parseSql('SELECT id FROM ipk').statement,local).result[0];assert.equal(r.columnIndex,-1);assert.deepEqual(r.descriptor,{name:'id',declaredType:'INTEGER',database:'main',table:'ipk',origin:'id',affinity:'integer',collation:'BINARY'});
 const aliased=expandAndResolveSelect(parseSql('SELECT id AS renamed FROM ipk').statement,local).result[0];assert.equal(aliased.columnIndex,-1);assert.equal(aliased.descriptor.name,'renamed');assert.equal(aliased.descriptor.origin,'id');assert.equal(aliased.descriptor.declaredType,'INTEGER');
});
