import assert from 'node:assert/strict';import test from 'node:test';import {encodeSql,tokenize} from '../../src/internal/tokenize.ts';import {parseSql,SqlParseError} from '../../src/internal/parse.ts';
const bad=[['1.0e+','1.0e'],['1.0E+','1.0E'],['1.0e-','1.0e'],['1.0E-','1.0E'],['1.0e+/','1.0e'],['1.0E+:','1.0E'],['1.0e-:','1.0e'],['1.0E-/','1.0E'],['1.0F+5','1.0F'],['1.0d-10','1.0d'],['1.0e,5','1.0e'],['1.0E.10','1.0E']];
for(let i=0;i<bad.length;i++)test(`upstream tokenize-1.${i+1}`,()=>assert.throws(()=>parseSql(`SELECT ${bad[i][0]}`),(e)=>e instanceof SqlParseError&&e.message===`unrecognized token: "${bad[i][1]}"`));
test('upstream tokenize-2.1 distinction',()=>assert.throws(()=>parseSql('SELECT 1, 2 /*'),/syntax error/));
test('upstream tokenize-2.2 distinction',()=>assert.equal(parseSql('SELECT 1, 2 /* ').statement?.kind,'select'));
test('src/tokenize.c numeric, BOM, and operator branches',()=>{const significant=s=>tokenize(encodeSql(s)).filter(t=>t.kind!=='eof');assert.deepEqual(significant('0x10').map(t=>[t.kind,t.text]),[['integer','0x10']]);assert.deepEqual(significant('0x10z').map(t=>[t.kind,t.text]),[['illegal','0x10z']]);assert.deepEqual(significant('\ufeffSELECT').map(t=>[t.kind,t.endByte-t.startByte]),[['space',3],['keyword',6]]);assert.deepEqual(significant('><').map(t=>[t.kind,t.text]),[['punct','>'],['punct','<']]);assert.deepEqual(significant('<< >> <> <= >= == !=').filter(t=>t.kind!=='space').map(t=>t.text),['<<','>>','<>','<=','>=','==','!=']);});
test('parse.y fallback and SELECT ownership regressions',()=>{assert.equal(parseSql('SELECT replace(\'a\',\'a\',\'b\')').statement?.kind,'select','REPLACE falls back by Lemon state, not spelling patch');const nested=parseSql('SELECT 7,(SELECT 8)').statement;assert.equal(nested?.kind,'select');assert.deepEqual(nested.result.map(e=>e.tokens.map(t=>t.text).join(' ')),['7','( SELECT 8 )']);assert.equal(nested.hasSubquery,true);const compound=parseSql('SELECT 1 UNION ALL SELECT 2').statement;assert.equal(compound?.kind,'select');assert.equal(compound.hasCompound,true);const values=parseSql('VALUES(1),(2)').statement;assert.equal(values?.kind,'select');assert.equal(values.hasValues,true);assert.equal(values.hasCompound,false);assert.equal(values.arms.length,1);assert.deepEqual(values.result.map(e=>e.tokens.map(t=>t.text).join(' ')),['1']);assert.deepEqual(values.arms[0].valuesRows.map(row=>row.map(e=>e.tokens.map(t=>t.text).join(' '))),[['1'],['2']]);});
test('tokenize.c contextual WINDOW/OVER/FILTER classification',()=>{assert.equal(parseSql('SELECT sum(1) OVER').statement?.kind,'select','OVER is an alias when analyzeOverKeyword returns ID');assert.equal(parseSql('SELECT sum(1) FILTER').statement?.kind,'select','FILTER is an alias unless RP is followed by LP');assert.equal(parseSql('SELECT window FROM t').statement?.kind,'select','WINDOW remains an ID outside WINDOW name AS');assert.equal(parseSql('SELECT sum(1) OVER ()').statement?.kind,'select','OVER remains a keyword before a window definition');assert.equal(parseSql('SELECT sum(1) FILTER (WHERE 1)').statement?.kind,'select','FILTER remains a keyword before LP');assert.equal(parseSql('SELECT 1 WINDOW win AS ()').statement?.kind,'select','WINDOW remains a keyword before identifier AS');});
test('quoted/comments/parameters/blob/keyword/non-ASCII byte spans',()=>{const t=tokenize(encodeSql('SELECT "é", :x, x\'0a\' -- 😀'));assert.equal(t[0]?.kind,'keyword');assert.equal(t.find(x=>x.text==='"é"')?.endByte,11);assert.equal(t.find(x=>x.text===':x')?.kind,'variable');assert.equal(t.find(x=>x.text==="x'0a'")?.kind,'blob');});
test('empty, UTF-8 tail, structures, syntax-vs-semantic seam',()=>{assert.equal(parseSql(' --x').statement,null);const p=parseSql('SELECT 😀; SELECT 2');assert.equal(p.tailOffset,12);assert.equal(p.tailCodeUnit,10);assert.equal(p.statement?.kind,'select');assert.equal(parseSql('SELECT * FROM t').statement?.kind,'select');assert.equal(parseSql('SELECT * FROM t').lemon?.accepted,true);assert.ok((parseSql('SELECT 1').lemon?.reductions.length??0)>0);assert.ok(parseSql('SELECT 1').lemon?.value,'reductions construct an immutable semantic value tree');const semantic=parseSql('SELECT 1').lemon?.value;const cmd=(function find(v){if(v?.kind==='reduction'&&v.signature.startsWith('cmd ::= select'))return v;for(const c of v?.kind==='reduction'?v.children:[]){const found=find(c);if(found)return found;}})(semantic);assert.equal(cmd?.semantic?.kind,'select','bounded semantic action executes on the Lemon cmd reduction');assert.throws(()=>parseSql('SELECT 1 garbage garbage'),SqlParseError);
const cte=parseSql('WITH x AS (SELECT 1) SELECT * FROM x');assert.equal(cte.statement?.kind,'select');assert.deepEqual(cte.statement.result[0]?.tokens.map(t=>t.text),['*']);assert.deepEqual(cte.statement.from.map(t=>t.text),['x']);
assert.throws(()=>parseSql('SELECT 1 [unterminated'),SqlParseError,'unknown or illegal terminals cannot bypass Lemon');assert.equal(parseSql('CREATE TABLE t(a INTEGER)').statement?.kind,'create-table');assert.throws(()=>parseSql('nonsense'),SqlParseError);});
test('generated CREATE TABLE reductions emit rich column semantics',()=>{const parsed=parseSql('CREATE TABLE t(a TEXT DEFAULT (lower("X")), b INTEGER GENERATED ALWAYS AS (length(a)) STORED, PRIMARY KEY(a,b)) WITHOUT ROWID');assert.equal(parsed.lemon?.accepted,true);assert.equal(parsed.statement?.kind,'create-table');assert.deepEqual(parsed.statement?.columns.map(c=>({name:c.name,declaredType:c.declaredType,default:c.defaultExpr?.tokens.map(t=>t.text).join(' ')??null,generated:c.generatedExpr?.tokens.map(t=>t.text).join(' ')??null})),[{name:'a',declaredType:'TEXT',default:'lower ( "X" )',generated:null},{name:'b',declaredType:'INTEGER',default:null,generated:'length ( a )'}]);assert.equal(parsed.statement.withoutRowid,true);});
test('generated WITH reductions own ordered immutable CTE semantics',()=>{
 const select=parseSql('WITH RECURSIVE A(x,y) AS MATERIALIZED (VALUES(1,2)), b AS NOT MATERIALIZED (SELECT x FROM A) SELECT * FROM b').statement;
 assert.equal(select?.kind,'select');assert.equal(select.with.recursive,true);
 assert.deepEqual(select.with.ctes.map(c=>({name:c.name,columns:c.columns,materialization:c.materialization})),[{name:'A',columns:['x','y'],materialization:'materialized'},{name:'b',columns:null,materialization:'not-materialized'}]);
 assert.equal(select.with.ctes[0].select.hasValues,true);assert.equal(select.with.ctes[1].select.from.items[0].tableName,'A');
 assert.ok(Object.isFrozen(select.with)&&Object.isFrozen(select.with.ctes)&&select.with.ctes.every(Object.isFrozen));
 assert.throws(()=>parseSql('WITH q AS (SELECT 1), Q AS (SELECT 2) SELECT * FROM q'),e=>e instanceof SqlParseError&&e.message==='duplicate WITH table name: Q');
});
test('generated parser must not be bypassed by recognized shift terminals',()=>{const parsed=parseSql('SELECT 1 << 2');assert.equal(parsed.statement?.kind,'select');assert.equal(parsed.lemon?.accepted,true,'recognized SQLite terminals must pass through generated Lemon tables');});
test('generated parser enforces configured work, stack, and full parse.y expression budgets',()=>{assert.throws(()=>parseSql('SELECT 1',{maxWorkUnits:1}),/maxWorkUnits/);assert.throws(()=>parseSql('SELECT 1',{maxParserDepth:1}),/maxParserDepth/);assert.throws(()=>parseSql('SELECT (((1+2)))',{maxExpressionDepth:2}),/maxExpressionDepth/);assert.throws(()=>parseSql('SELECT 1+2+3+4',{maxExpressionDepth:2}),/maxExpressionDepth/);assert.equal(parseSql('SELECT (1+2)',{maxWorkUnits:1000,maxParserDepth:100,maxExpressionDepth:3}).statement?.kind,'select');});
test('arm-local ORDER recovery cannot publish a partial compound graph',()=>{assert.throws(()=>parseSql('SELECT 1 ORDER BY 1 UNION ALL SELECT 2'),e=>e instanceof SqlParseError&&e.message==='ORDER BY clause should come after UNION ALL not before');});

test('generated SELECT reductions own immutable child semantics',()=>{
 const {lemon,statement}=parseSql('VALUES(1),(2),(3) UNION ALL SELECT 4');assert.ok(statement&&statement.kind==='select');
 const reductions=[];const walk=n=>{if(n?.kind==='reduction'){reductions.push(n);for(const c of n.children)walk(c)}};walk(lemon.value);
 for(const signature of ['values ::= VALUES LP nexprlist RP','mvalues ::= values COMMA LP nexprlist RP','oneselect ::= mvalues','selectnowith ::= oneselect','selectnowith ::= selectnowith multiselect_op oneselect','select ::= selectnowith','cmd ::= select']){const n=reductions.find(n=>n.signature===signature);assert.ok(n,`required generated owner did not reduce: ${signature}`);assert.notEqual(n.semantic,undefined,signature)}
 for(const n of reductions.filter(n=>n.signature.startsWith('oneselect ::= SELECT ')))assert.notEqual(n.semantic,undefined,n.signature);
 assert.deepEqual(statement.arms.map(a=>[a.origin,a.prior,a.next,a.operatorFromPrior]),[['values',null,1,null],['select',0,null,'union-all']]);assert.deepEqual(statement.arms[0].valuesRows.map(row=>row[0].tokens[0].text),['1','2','3']);assert.ok(Object.isFrozen(statement.arms)&&statement.arms.every(Object.isFrozen));
});
test('parse.y SrcList actions preserve ordered immutable source and RHS join ownership',()=>{
 const select=parseSql('SELECT * FROM a AS aa LEFT JOIN main.b bb USING(x,x), c CROSS JOIN d ON c.z=d.z').statement;
 assert.equal(select?.kind,'select');
 assert.deepEqual(select.from.items.map(({databaseName,tableName,alias,using,joinFromLeft})=>({databaseName,tableName,alias,using,joinFromLeft})),[
  {databaseName:null,tableName:'a',alias:'aa',using:null,joinFromLeft:{inner:true,cross:false,natural:false,left:false,right:false,outer:false,error:false}},
  {databaseName:'main',tableName:'b',alias:'bb',using:['x','x'],joinFromLeft:{inner:false,cross:false,natural:false,left:true,right:false,outer:false,error:false}},
  {databaseName:null,tableName:'c',alias:null,using:null,joinFromLeft:{inner:true,cross:false,natural:false,left:false,right:false,outer:false,error:false}},
  {databaseName:null,tableName:'d',alias:null,using:null,joinFromLeft:{inner:false,cross:true,natural:false,left:false,right:false,outer:false,error:false}},
 ]);
 assert.deepEqual(select.from.items[3].on.tokens.map(token=>token.text),['c','.','z','=','d','.','z']);
 assert.ok(Object.isFrozen(select.from)&&Object.isFrozen(select.from.items)&&select.from.items.every(Object.isFrozen));
 const right=parseSql('SELECT * FROM a RIGHT JOIN b ON 1 FULL JOIN c USING(x)').statement;
 assert.deepEqual(right.from.items.map(item=>[item.joinFromLeft.left,item.joinFromLeft.right,item.leftOfRightJoin]),[[false,false,true],[false,true,true],[true,true,false]]);
});

test('generated CREATE TABLE reductions retain CHECK and foreign-key semantics',()=>{const parsed=parseSql('CREATE TABLE t(a CHECK(a>0), b, CONSTRAINT ck CHECK(a<>b), CONSTRAINT fk FOREIGN KEY(a,b) REFERENCES p(x,y) ON DELETE CASCADE ON UPDATE SET NULL DEFERRABLE INITIALLY DEFERRED)');assert.equal(parsed.statement?.kind,'create-table');if(parsed.statement?.kind!=='create-table')return;assert.deepEqual(parsed.statement.checks.map(check=>({name:check.name,column:check.columnName,expr:check.expr.tokens.map(t=>t.text).join('')})),[{name:null,column:'a',expr:'a>0'},{name:'ck',column:null,expr:'a<>b'}]);assert.deepEqual(parsed.statement.foreignKeys.map(foreign=>({name:foreign.name,columns:foreign.columns,table:foreign.referencedTable,to:foreign.referencedColumns,del:foreign.onDelete,update:foreign.onUpdate,deferrable:foreign.deferrable,deferred:foreign.initiallyDeferred})),[{name:'fk',columns:['a','b'],table:'p',to:['x','y'],del:'cascade',update:'set-null',deferrable:true,deferred:true}]);assert.ok(Object.isFrozen(parsed.statement.checks)&&Object.isFrozen(parsed.statement.foreignKeys));});
