import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {startFixtureServer} from './fixture-server.mjs';
import {openFixture} from './public-api-adapter.mjs';
import {open,JSQLiteError} from '../../src/index.ts';
import {SorterCursor,EphemeralIndexCursor} from '../../src/internal/private-state.ts';
const root=path.resolve('test/fixtures');
async function server(){return startFixtureServer(root)}
async function connect(bridge,fixture='expr-relational',options){const r=new Request(`http://127.0.0.1:${bridge.port}/fixture/${bridge.token}/${fixture}`);return options?open(r,options):openFixture(r)}
async function values(db,sql){const s=db.prepare(sql).statement,out=[];try{while(await s.step()==='row')out.push(Array.from({length:s.columnCount},(_,i)=>s.column(i)));return out}finally{s.finalize()}}
async function closeServer(bridge){await new Promise((r,j)=>bridge.server.close(e=>e?j(e):r()))}

test('grouped result DISTINCT uses typed ephemeral equality before ORDER',async()=>{const b=await server();let db;try{db=await connect(b);assert.deepEqual(await values(db,'SELECT DISTINCT y%2 FROM t1 GROUP BY y ORDER BY 1'),[[0n],[1n]]);assert.deepEqual(await values(db,'SELECT DISTINCT min(NULL) FROM t1 GROUP BY y ORDER BY 1'),[[null]])}finally{try{db?.closeDeferred()}catch{}await closeServer(b)}});

test('grouped result DISTINCT preserves collation and all database encodings',async()=>{const b=await server();let db;try{db=await connect(b,'expr-where');assert.deepEqual(await values(db,'SELECT DISTINCT a COLLATE nocase FROM t GROUP BY a COLLATE nocase ORDER BY 1'),[[null],['abc'],['XYZ']]);db.close();db=undefined;for(const fixture of ['encoding-utf8','encoding-utf16le','encoding-utf16be']){db=await connect(b,fixture);assert.deepEqual(await values(db,'SELECT DISTINCT a COLLATE nocase FROM t1 GROUP BY a COLLATE nocase ORDER BY 1'),[['one']],fixture);db.close();db=undefined}}finally{try{db?.closeDeferred()}catch{}await closeServer(b)}});

test('grouped DISTINCT reset after yield and completion rebuilds private cursors',async()=>{const b=await server();let db,s;try{db=await connect(b);s=db.prepare('SELECT DISTINCT y%2 FROM t1 GROUP BY y ORDER BY 1').statement;assert.equal(await s.step(),'row');assert.equal(s.column(0),0n);s.reset();assert.deepEqual(await drain(s),[0n,1n]);s.reset();assert.deepEqual(await drain(s),[0n,1n]);s.finalize();s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await closeServer(b)}});
async function drain(s){const out=[];while(await s.step()==='row')out.push(s.column(0));return out}

test('grouped DISTINCT enforces shared private entry/key/byte limits and restores admission',async()=>{const b=await server();try{for(const [limits,text] of [[{maxPrivateEntries:0},'entry limit'],[{maxPrivateKeyBytes:0},'key exceeds byte limit'],[{maxPrivateBytes:0},'total byte limit']]){let db,s;try{db=await connect(b,'expr-relational',{limits:{maxRows:100,maxResultBytes:1000,...limits}});s=db.prepare('SELECT DISTINCT y%2 FROM t1 GROUP BY y ORDER BY 1').statement;await assert.rejects(s.step(),e=>e instanceof JSQLiteError&&e.kind==='limit'&&e.message.includes(text));assert.throws(()=>s.reset(),e=>e.kind==='limit');s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}}}}finally{await closeServer(b)}});

test('group sorter suspension observes cancellation, preserves first error, resets and finalizes',async()=>{const sort=SorterCursor.prototype.sort,close=SorterCursor.prototype.close,timer=globalThis.setTimeout;let release,reached,closes=0,inject=true;const suspended=new Promise(r=>reached=r);SorterCursor.prototype.sort=async function(control){if(inject)for(let i=0;i<300;i++)await control.checkpoint(1);return sort.call(this,control)};SorterCursor.prototype.close=function(){closes++;return close.call(this)};globalThis.setTimeout=(cb,ms,...args)=>{if(ms===0&&!release){release=()=>timer(cb,0,...args);reached();return 0}return timer(cb,ms,...args)};const b=await server();let db,s;try{db=await connect(b);s=db.prepare('SELECT y,count(*) FROM t1 GROUP BY y ORDER BY y').statement;const c=new AbortController(),pending=s.step({signal:c.signal});await suspended;assert.throws(()=>db.prepare('SELECT 1'),e=>e.kind==='misuse');c.abort('aggregate-stop');release();await assert.rejects(pending,e=>e.kind==='cancelled'&&e.cause==='aggregate-stop');assert.equal(closes,1);assert.throws(()=>s.reset(),e=>e.kind==='cancelled');inject=false;assert.equal((await drain(s)).length,10);s.finalize();s=undefined;assert.equal(closes,2);const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{globalThis.setTimeout=timer;SorterCursor.prototype.sort=sort;SorterCursor.prototype.close=close;try{release?.()}catch{}try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await closeServer(b)}});

test('group sorter deadline/work failures retain first error and clean up',async()=>{const sort=SorterCursor.prototype.sort,now=Date.now;let active=false;SorterCursor.prototype.sort=async function(control){active=true;await control.checkpoint(1);return sort.call(this,control)};Date.now=()=>active?100:0;const b=await server();let db,s;try{db=await connect(b);s=db.prepare('SELECT y,count(*) FROM t1 GROUP BY y').statement;await assert.rejects(s.step({timeoutMs:2}),e=>e.kind==='timeout');assert.throws(()=>s.finalize(),e=>e.kind==='timeout');s=undefined;Date.now=now;active=false;s=db.prepare('SELECT y,count(*) FROM t1 GROUP BY y').statement;await assert.rejects(s.step({maxWorkUnits:0}),e=>e.kind==='limit'&&e.message==='statement exceeds maxWorkUnits');assert.throws(()=>s.finalize(),e=>e.kind==='limit');s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{Date.now=now;SorterCursor.prototype.sort=sort;try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await closeServer(b)}});

test('grouped DISTINCT insertion failure remains authoritative over cleanup failure',async()=>{const insert=EphemeralIndexCursor.prototype.insert,close=EphemeralIndexCursor.prototype.close;const primary=new RangeError('aggregate distinct insert failure'),cleanup=new Error('aggregate distinct close failure');let fail=true;EphemeralIndexCursor.prototype.insert=function(...args){if(fail)throw primary;return insert.apply(this,args)};EphemeralIndexCursor.prototype.close=function(){close.call(this);if(fail)throw cleanup};const b=await server();let db,s;try{db=await connect(b);s=db.prepare('SELECT DISTINCT y%2 FROM t1 GROUP BY y').statement;await assert.rejects(s.step(),e=>e===primary);assert.throws(()=>s.reset(),e=>e===primary);fail=false;assert.deepEqual((await drain(s)).sort(),[0n,1n]);s.finalize();s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{EphemeralIndexCursor.prototype.insert=insert;EphemeralIndexCursor.prototype.close=close;try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await closeServer(b)}});

test('min/max retained text and blob share the private byte budget and release it',async()=>{const b=await server();try{
 for(const [sql,expected,bytes] of [
  ["SELECT min(a) FROM t",'abc',3],
  ["SELECT max(CASE x WHEN 31 THEN 'a' ELSE 'longer' END) FROM t1 WHERE x>=30",'longer',6],
  ["SELECT min(CASE x WHEN 31 THEN 'longer' ELSE 'a' END) FROM t1 WHERE x>=30",'a',6],
  ["SELECT max(CAST(a AS BLOB)) FROM t",new Uint8Array([97,98,99]),3],
 ]){let db,s;try{const fixture=sql.includes('t1')?'expr-relational':'expr-where';db=await connect(b,fixture,{limits:{maxRows:100,maxResultBytes:1000,maxPrivateBytes:bytes}});s=db.prepare(sql).statement;assert.equal(await s.step(),'row');assert.deepEqual(s.column(0),expected);s.reset();assert.equal(await s.step(),'row');assert.deepEqual(s.column(0),expected);s.finalize();s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}}}
 let db,s;try{db=await connect(b,'expr-where',{limits:{maxRows:100,maxResultBytes:1000,maxPrivateBytes:2}});s=db.prepare('SELECT min(a) FROM t').statement;await assert.rejects(s.step(),e=>e instanceof JSQLiteError&&e.kind==='limit'&&e.message==='aggregate state exceeds total byte limit');assert.throws(()=>s.reset(),e=>e.kind==='limit');s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}}
}finally{await closeServer(b)}});

test('aggregate-local DISTINCT and ordered queues release budget after failure',async()=>{const b=await server();try{for(const sql of ['SELECT count(DISTINCT a) FROM t','SELECT group_concat(a ORDER BY a) FROM t']){let db,s;try{db=await connect(b,'expr-where',{limits:{maxRows:100,maxResultBytes:1000,maxPrivateBytes:2}});s=db.prepare(sql).statement;await assert.rejects(s.step(),e=>e instanceof JSQLiteError&&e.kind==='limit');assert.throws(()=>s.reset(),e=>e.kind==='limit');s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}}}}finally{await closeServer(b)}});
