import assert from 'node:assert/strict';import path from 'node:path';import test from 'node:test';import {startFixtureServer} from './fixture-server.mjs';import {openFixture} from './public-api-adapter.mjs';
import {open,JSQLiteError} from '../../src/index.ts';
import {EphemeralIndexCursor} from '../../src/internal/private-state.ts';
const root=path.resolve(new URL('../fixtures',import.meta.url).pathname);
async function withDb(fn){const b=await startFixtureServer(root);let db;try{db=await openFixture(new Request(`http://127.0.0.1:${b.port}/fixture/${b.token}/empty`));await fn(db)}finally{try{db?.closeDeferred()}catch{}await new Promise((r,j)=>b.server.close(e=>e?j(e):r()))}}
test('unordered scalar UNION ALL preserves arm order/multiplicity and leftmost name',()=>withDb(async db=>{const s=db.prepare('SELECT 2 AS v UNION ALL SELECT 1 UNION ALL SELECT 2').statement;try{assert.equal(s.columnMetadata(0).name,'v');const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,[2n,1n,2n])}finally{s.finalize()}}));
test('compound LIMIT/OFFSET is global and coerced at first step',()=>withDb(async db=>{let s=db.prepare('SELECT 3 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 LIMIT 1 OFFSET 1').statement;try{assert.equal(await s.step(),'row');assert.equal(s.column(0),1n);assert.equal(await s.step(),'done')}finally{s.finalize()}s=db.prepare("SELECT 1 UNION ALL SELECT 2 LIMIT 'x'").statement;await assert.rejects(()=>s.step(),e=>e?.kind==='sqlite'&&e?.code===20);assert.throws(()=>s.finalize(),e=>e?.code===20)}));
test('width mismatch rejects before any arm can execute',()=>withDb(async db=>{assert.throws(()=>db.prepare('SELECT 1 UNION ALL SELECT 2,3'),e=>e?.kind==='sqlite'&&e?.code===1)}));
test('unordered UNION uses typed ephemeral equality and right representative',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 2 AS v UNION SELECT 1 UNION SELECT 2',[1n,2n]],['SELECT NULL AS v UNION SELECT NULL',[null]],['SELECT 1 AS v UNION SELECT 1.0',[1]], ["SELECT 1 AS v UNION SELECT '1'",[1n,'1']]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));
test('scalar INTERSECT/EXCEPT and mixed operators apply left-to-right set transitions',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 1 AS v UNION ALL SELECT 1 INTERSECT SELECT 1',[1n]],['SELECT 1 AS v UNION SELECT 2 EXCEPT SELECT 1',[2n]],['SELECT 1 AS v UNION SELECT 2 INTERSECT SELECT 2',[2n]],['SELECT 1 AS v UNION SELECT 2 EXCEPT SELECT 3',[1n,2n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));
test('set-route LIMIT/OFFSET applies after duplicate/set transitions',()=>withDb(async db=>{let s=db.prepare('SELECT 3 AS v UNION SELECT 1 UNION SELECT 2 LIMIT 1 OFFSET 1').statement;try{assert.equal(await s.step(),'row');assert.equal(s.column(0),2n);assert.equal(await s.step(),'done')}finally{s.finalize()}s=db.prepare("SELECT 1 UNION SELECT 2 LIMIT 'x'").statement;await assert.rejects(()=>s.step(),e=>e?.kind==='sqlite'&&e?.code===20);assert.throws(()=>s.finalize(),e=>e?.code===20)}));
test('single-column set ORDER resolves aliases, ordinals, and matching result expressions',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 2 AS v UNION SELECT 1 UNION SELECT 2 ORDER BY v',[1n,2n]],['SELECT 1 AS v UNION SELECT 2 ORDER BY 1 DESC',[2n,1n]],['SELECT 2+1 AS v UNION SELECT 1+1 ORDER BY 2+1',[2n,3n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}assert.throws(()=>db.prepare('SELECT 1 AS v UNION SELECT 2 ORDER BY missing'),e=>e?.kind==='sqlite'&&e?.code===1)}));
test('ordered UNION ALL uses stable typed sorter and compound-wide LIMIT',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 3 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 ORDER BY v',[1n,2n,3n]],['SELECT 2+1 AS v UNION ALL SELECT 1+1 ORDER BY 2+1',[2n,3n]],['SELECT 3 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 ORDER BY v LIMIT 1 OFFSET 1',[2n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));
test('ordered UNION ALL compares every ORDER term across multi-column arms',()=>withDb(async db=>{const s=db.prepare('SELECT 1 AS a,2 AS b UNION ALL SELECT 1,1 UNION ALL SELECT 0,9 ORDER BY a,b').statement;try{assert.equal(s.columnMetadata(0).name,'a');assert.equal(s.columnMetadata(1).name,'b');const rows=[];while(await s.step()==='row')rows.push([s.column(0),s.column(1)]);assert.deepEqual(rows,[[0n,9n],[1n,1n],[1n,2n]])}finally{s.finalize()}}));
test('ordered compound reset after a yielded row restarts all producers',()=>withDb(async db=>{const sql='SELECT 1 AS a,2 AS b UNION ALL SELECT 1,1 UNION ALL SELECT 0,9 UNION ALL SELECT 2,0 ORDER BY a,b LIMIT 2 OFFSET 1';const s=db.prepare(sql).statement;try{assert.equal(await s.step(),'row');assert.deepEqual([s.column(0),s.column(1)],[1n,1n]);s.reset();const rows=[];while(await s.step()==='row')rows.push([s.column(0),s.column(1)]);assert.deepEqual(rows,[[1n,1n],[1n,2n]],'reset rebuilds the ordered compound from its first producer rather than resuming after the yield')}finally{s.finalize()}const admitted=db.prepare('SELECT 99').statement;try{assert.equal(await admitted.step(),'row');assert.equal(admitted.column(0),99n)}finally{admitted.finalize()}}));
test('table compound set-to-UNION-ALL handoff preserves the collapsed prefix then suffix multiplicity',async()=>{const bridge=await startFixtureServer(root);let db;try{db=await openFixture(new Request(`http://127.0.0.1:${bridge.port}/fixture/${bridge.token}/compound-metadata`));const s=db.prepare('SELECT a AS v FROM left_meta UNION SELECT b FROM right_meta UNION ALL SELECT a FROM left_meta').statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,[7n,'8',7n]);assert.equal(s.columnMetadata(0).name,'v')}finally{s.finalize()}}finally{try{db?.closeDeferred()}catch{}await new Promise((r,j)=>bridge.server.close(e=>e?j(e):r()))}});
test('structured VALUES arms participate without fabricated UNION parsing',()=>withDb(async db=>{for(const [sql,expected] of [["VALUES(2),(1) UNION ALL SELECT 3",[2n,1n,3n]],["VALUES(2),(1),(1) UNION SELECT 2",[1n,2n]],["VALUES(1),(2) INTERSECT VALUES(2),(3)",[2n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));

test('compound private state enforces row and byte bounds and restores admission',async()=>{
 const bridge=await startFixtureServer(root);let db,s;
 const url=new Request(`http://127.0.0.1:${bridge.port}/fixture/${bridge.token}/compound-metadata`),sql='SELECT a FROM left_meta UNION SELECT b FROM right_meta UNION ALL SELECT a FROM left_meta';
 try{
  for(const [limits,message] of [[{maxRows:1,maxResultBytes:64},'ephemeral index exceeds entry limit'],[{maxRows:8,maxResultBytes:0},'ephemeral key exceeds byte limit']]){
   db=await open(url.clone(),{limits});s=db.prepare(sql).statement;await assert.rejects(s.step(),e=>e instanceof JSQLiteError&&e.kind==='limit'&&e.message===message);assert.throws(()=>s.reset(),e=>e.kind==='limit');s=undefined;db.closeDeferred();db=undefined;
  }
  db=await open(url.clone(),{limits:{maxRows:8,maxResultBytes:64}});s=db.prepare(sql).statement;const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,[7n,'8',7n]);s.finalize();s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize();
 }finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>bridge.server.close(e=>e?j(e):r()))}
});

test('compound active suspension preserves PC, exclusive admission, cancellation, cleanup, reset and finalize',async()=>{
 const timer=globalThis.setTimeout;let release,reached;const suspended=new Promise(r=>{reached=r});globalThis.setTimeout=(cb,ms,...args)=>{if(ms===0&&!release){release=()=>timer(cb,0,...args);reached();return 0}return timer(cb,ms,...args)};
 const bridge=await startFixtureServer(root);let db,s;
 try{db=await openFixture(new Request(`http://127.0.0.1:${bridge.port}/fixture/${bridge.token}/expr-relational`));const sql=Array.from({length:10},()=> 'SELECT x FROM t1').join(' UNION ALL ');s=db.prepare(sql).statement;const abort=new AbortController(),pending=(async()=>{while(await s.step({signal:abort.signal})==='row'){} })();await suspended;assert.throws(()=>db.prepare('SELECT 1'),e=>e.kind==='misuse');await assert.rejects(s.step(),e=>e.kind==='misuse');abort.abort('compound-stop');release();await assert.rejects(pending,e=>e.kind==='cancelled'&&e.cause==='compound-stop');assert.throws(()=>s.reset(),e=>e.kind==='cancelled');globalThis.setTimeout=timer;let count=0;while(await s.step()==='row')count++;assert.equal(count,320,'reset executes each arm once without restart or duplicates');s.finalize();s=undefined;const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}
 finally{globalThis.setTimeout=timer;try{release?.()}catch{}try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>bridge.server.close(e=>e?j(e):r()))}
});

test('compound deadline and exact work bound keep first error and cleanup',async()=>{
 const insert=EphemeralIndexCursor.prototype.insert,now=Date.now;let active=false;EphemeralIndexCursor.prototype.insert=async function(key,control){active=true;await control.checkpoint(1);return insert.call(this,key,control)};Date.now=()=>active?100:0;
 const bridge=await startFixtureServer(root);let db,s;
 try{db=await openFixture(new Request(`http://127.0.0.1:${bridge.port}/fixture/${bridge.token}/compound-metadata`));s=db.prepare('SELECT a FROM left_meta UNION SELECT b FROM right_meta').statement;await assert.rejects(s.step({timeoutMs:2}),e=>e.kind==='timeout');assert.throws(()=>s.finalize(),e=>e.kind==='timeout');s=undefined;Date.now=now;const limited=db.prepare('SELECT a FROM left_meta UNION SELECT b FROM right_meta').statement;await assert.rejects(limited.step({maxWorkUnits:0}),e=>e.kind==='limit');assert.throws(()=>limited.finalize(),e=>e.kind==='limit');const admitted=db.prepare('SELECT 1').statement;assert.equal(await admitted.step(),'row');admitted.finalize()}
 finally{Date.now=now;EphemeralIndexCursor.prototype.insert=insert;try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>bridge.server.close(e=>e?j(e):r()))}
});

test('ordered mixed table compound uses one typed global merge with LIMIT',async()=>{
 const bridge=await startFixtureServer(root);let db,s;try{db=await openFixture(new Request(`http://127.0.0.1:${bridge.port}/fixture/${bridge.token}/compound-metadata`));
 for(const [sql,expected] of [['SELECT a AS v FROM left_meta UNION SELECT b FROM right_meta UNION ALL SELECT a FROM left_meta ORDER BY v DESC',["8",7n,7n]],['SELECT a AS v FROM left_meta UNION SELECT b FROM right_meta UNION ALL SELECT a FROM left_meta ORDER BY 1 DESC LIMIT 2 OFFSET 1',[7n,7n]]]){s=db.prepare(sql).statement;const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected);assert.equal(s.columnMetadata(0).name,'v');s.finalize();s=undefined}
 assert.throws(()=>db.prepare('SELECT a AS v FROM left_meta UNION SELECT b FROM right_meta UNION ALL SELECT a FROM left_meta ORDER BY missing'),e=>e.kind==='sqlite'&&e.code===1);
 }finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>bridge.server.close(e=>e?j(e):r()))}
});

test('table INTERSECT preserves the left representative across INTEGER/REAL equality',async()=>{
 const bridge=await startFixtureServer(root);let db,s;try{db=await openFixture(new Request(`http://127.0.0.1:${bridge.port}/fixture/${bridge.token}/storage-p4096`));
 const cases=[
  ['SELECT i AS v FROM storage_values INTERSECT SELECT r FROM storage_values ORDER BY v',[0n,1n]],
  ['SELECT i AS v FROM storage_values INTERSECT SELECT r FROM storage_values UNION ALL SELECT i FROM storage_values ORDER BY v LIMIT 6',[-9223372036854775808n,0n,0n,1n,1n,2n]],
 ];
 for(const [sql,expected] of cases){s=db.prepare(sql).statement;const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected);s.finalize();s=undefined}
 }finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>bridge.server.close(e=>e?j(e):r()))}
});
