import assert from 'node:assert/strict';import path from 'node:path';import test from 'node:test';import {startFixtureServer} from './fixture-server.mjs';import {openFixture} from './public-api-adapter.mjs';
const root=path.resolve(new URL('../fixtures',import.meta.url).pathname);
async function withDb(fn){const b=await startFixtureServer(root);let db;try{db=await openFixture(new Request(`http://127.0.0.1:${b.port}/fixture/${b.token}/empty`));await fn(db)}finally{try{db?.closeDeferred()}catch{}await new Promise((r,j)=>b.server.close(e=>e?j(e):r()))}}
test('unordered scalar UNION ALL preserves arm order/multiplicity and leftmost name',()=>withDb(async db=>{const s=db.prepare('SELECT 2 AS v UNION ALL SELECT 1 UNION ALL SELECT 2').statement;try{assert.equal(s.columnMetadata(0).name,'v');const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,[2n,1n,2n])}finally{s.finalize()}}));
test('compound LIMIT/OFFSET is global and coerced at first step',()=>withDb(async db=>{let s=db.prepare('SELECT 3 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 LIMIT 1 OFFSET 1').statement;try{assert.equal(await s.step(),'row');assert.equal(s.column(0),1n);assert.equal(await s.step(),'done')}finally{s.finalize()}s=db.prepare("SELECT 1 UNION ALL SELECT 2 LIMIT 'x'").statement;await assert.rejects(()=>s.step(),e=>e?.kind==='sqlite'&&e?.code===20);assert.throws(()=>s.finalize(),e=>e?.code===20)}));
test('width mismatch rejects before any arm can execute',()=>withDb(async db=>{assert.throws(()=>db.prepare('SELECT 1 UNION ALL SELECT 2,3'),e=>e?.kind==='sqlite'&&e?.code===1)}));
test('unordered UNION uses typed ephemeral equality and right representative',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 2 AS v UNION SELECT 1 UNION SELECT 2',[1n,2n]],['SELECT NULL AS v UNION SELECT NULL',[null]],['SELECT 1 AS v UNION SELECT 1.0',[1]], ["SELECT 1 AS v UNION SELECT '1'",[1n,'1']]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));
test('scalar INTERSECT/EXCEPT and mixed operators apply left-to-right set transitions',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 1 AS v UNION ALL SELECT 1 INTERSECT SELECT 1',[1n]],['SELECT 1 AS v UNION SELECT 2 EXCEPT SELECT 1',[2n]],['SELECT 1 AS v UNION SELECT 2 INTERSECT SELECT 2',[2n]],['SELECT 1 AS v UNION SELECT 2 EXCEPT SELECT 3',[1n,2n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));
test('set-route LIMIT/OFFSET applies after duplicate/set transitions',()=>withDb(async db=>{let s=db.prepare('SELECT 3 AS v UNION SELECT 1 UNION SELECT 2 LIMIT 1 OFFSET 1').statement;try{assert.equal(await s.step(),'row');assert.equal(s.column(0),2n);assert.equal(await s.step(),'done')}finally{s.finalize()}s=db.prepare("SELECT 1 UNION SELECT 2 LIMIT 'x'").statement;await assert.rejects(()=>s.step(),e=>e?.kind==='sqlite'&&e?.code===20);assert.throws(()=>s.finalize(),e=>e?.code===20)}));
test('single-column set ORDER resolves aliases, ordinals, and matching result expressions',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 2 AS v UNION SELECT 1 UNION SELECT 2 ORDER BY v',[1n,2n]],['SELECT 1 AS v UNION SELECT 2 ORDER BY 1 DESC',[2n,1n]],['SELECT 2+1 AS v UNION SELECT 1+1 ORDER BY 2+1',[2n,3n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}assert.throws(()=>db.prepare('SELECT 1 AS v UNION SELECT 2 ORDER BY missing'),e=>e?.kind==='sqlite'&&e?.code===1)}));
test('ordered UNION ALL uses stable typed sorter and compound-wide LIMIT',()=>withDb(async db=>{for(const [sql,expected] of [['SELECT 3 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 ORDER BY v',[1n,2n,3n]],['SELECT 2+1 AS v UNION ALL SELECT 1+1 ORDER BY 2+1',[2n,3n]],['SELECT 3 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 ORDER BY v LIMIT 1 OFFSET 1',[2n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));
test('structured VALUES arms participate without fabricated UNION parsing',()=>withDb(async db=>{for(const [sql,expected] of [["VALUES(2),(1) UNION ALL SELECT 3",[2n,1n,3n]],["VALUES(2),(1),(1) UNION SELECT 2",[1n,2n]],["VALUES(1),(2) INTERSECT VALUES(2),(3)",[2n]]]){const s=db.prepare(sql).statement;try{const rows=[];while(await s.step()==='row')rows.push(s.column(0));assert.deepEqual(rows,expected)}finally{s.finalize()}}}));
