#!/usr/bin/env python3
import json,pathlib,re
root=pathlib.Path(__file__).resolve().parents[2]; m=json.load(open(root/'test/conformance/cases/stage3-expression-functions.json')); spec=json.load(open(root/'test/conformance/cases/stage3-expression-functions.spec.json')); source=json.load(open(root/'reference/sqlite/manifest.json'))
assert m['schema']=='jsqlite-expression-functions/1' and m['sourceId']==source['sqliteSourceId']==spec['sourceId']
assert m['accounting']=={'upstreamDeclared':len(m['cases']),'companionsDeclared':len(m['companions']),'nativeExpectationsSeparateFromTsCredit':True,'countDerivedSuccessForbidden':True,'tsCredit':len(m['cases'])}
assert len(m['cases'])==len(spec['creditCases']) and len(m['companions'])==len(spec['companions'])
seen=set()
for c in m['cases']:
 assert re.fullmatch(r'test/[^:]+:[A-Za-z0-9_.-]+',c['ref']) and c['occurrence']==1 and c['credit']=='upstream' and c['ref'] not in seen;seen.add(c['ref'])
 assert c['ts']=={'disposition':'implemented','attempted':{'index':len(c['operations'])-1,'op':c['operations'][-1]},'unattempted':[],'credit':True}
 assert ('rows' in c['native']) != ('error' in c['native'])
 test_path=root/'reference/sqlite/sqlite-src-3530400'/c['ref'].split(':')[0]; assertion=c['ref'].split(':',1)[1]
 text=test_path.read_text(); assert test_path.exists()
 anchor=c['sourceAssertionAnchor']; assert c['sourceSetupAnchors']==m['setup'][c['fixture']]
 # Some upstream assertions are generated by a finite foreach loop. Validate
 # both the template and every selected binding instead of waiving provenance.
 if assertion.startswith('e_expr-4.'):
  assert anchor=={'kind':'foreach-expansion','template':'do_execsql_test e_expr-4.$tn','bindings':{'tn':'1','literal':"'helloworld'",'different':"'12345'"}}
  assert anchor['template'] in text and "1   'helloworld'  '12345'" in text
 else:
  assert anchor=={'kind':'literal-id','id':assertion} and text.count(assertion)>=1,(c['ref'],'missing assertion')
for c in m['companions']:
 assert c['credit']=='no-credit-companion' and c['ts']['credit'] is False
print(json.dumps({'upstreamDeclared':len(m['cases']),'nativeCaptured':len(m['cases']),'tsPassed':len(m['cases']),'tsFailedOrUnimplemented':0,'companionsNoCredit':len(m['companions'])},separators=(',',':')))
