import assert from 'node:assert/strict';
import fs from 'node:fs';import http from 'node:http';import path from 'node:path';import test from 'node:test';
import {openFixture} from './public-api-adapter.mjs';
const capture=JSON.parse(fs.readFileSync(new URL('./cases/stage3-multisource-select.json',import.meta.url),'utf8'));
const selected=new Set(['comma-order','cross','inner-on-alias','bare-star-using','qualified-star-using','natural','duplicate-names','affinity-collation','distinct-order-limit','on-result-alias']);
const cases=capture.cases.filter(c=>selected.has(c.id));
const negativeSelected=new Set(['ambiguous','no-such-column','alias-hides-table','bad-star-qualifier','natural-on-error','using-missing-error']);
const negativeCases=capture.cases.filter(c=>negativeSelected.has(c.id));
function value(v){if(v.type==='null')return null;if(v.type==='integer')return BigInt(v.value);if(v.type==='real')return Number(v.value);if(v.type==='text')return Buffer.from(v.utf8Hex,'hex').toString();if(v.type==='blob')return new Uint8Array(Buffer.from(v.hex,'hex'));throw Error(`unknown ${v.type}`)}
async function serve(file='./fixtures/multisource-inner-oracle.db'){const body=fs.readFileSync(new URL(file,import.meta.url));const server=http.createServer((req,res)=>{if(req.url!='/db'){res.writeHead(404).end();return}res.writeHead(200,{'Content-Type':'application/vnd.sqlite3','Content-Length':body.length});res.end(body)});await new Promise((r,j)=>server.listen(0,'127.0.0.1',r).once('error',j));return server}
test('public INNER subset matches pinned 3.53.4 multisource capture',async()=>{assert.equal(cases.length,10);const server=await serve();let db,s;try{db=await openFixture(new Request(`http://127.0.0.1:${server.address().port}/db`));for(const c of cases){s=db.prepare(c.sql).statement;assert.deepEqual(Array.from({length:s.columnCount},(_,i)=>{const m=s.columnMetadata(i);return{name:m.name,declType:m.declaredType,database:m.database,table:m.table,origin:m.origin}}),c.native.columns,c.id+' metadata');const actual=[];while(await s.step()==='row')actual.push(Array.from({length:s.columnCount},(_,i)=>s.column(i)));assert.deepEqual(actual,c.native.first.rows.map(r=>r.map(value)),c.id+' rows');s.finalize();s=null}}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>server.close(e=>e?j(e):r()))}});

test('public INNER prepare errors match pinned 3.53.4 multisource capture',async()=>{assert.equal(negativeCases.length,6);const server=await serve();let db;try{db=await openFixture(new Request(`http://127.0.0.1:${server.address().port}/db`));for(const c of negativeCases){const expected=c.native.prepare;assert.throws(()=>db.prepare(c.sql),error=>error.kind==='sqlite'&&error.code===expected.resultCode&&error.extendedCode===expected.extendedCode&&error.message===expected.message,c.id)}}finally{try{db?.closeDeferred()}catch{}await new Promise((r,j)=>server.close(e=>e?j(e):r()))}});

test('public INNER reset and rebind match pinned 3.53.4 multisource capture',async()=>{const c=capture.cases.find(c=>c.id==='reset-rebind');assert.ok(c);const server=await serve();let db,s;try{db=await openFixture(new Request(`http://127.0.0.1:${server.address().port}/db`));s=db.prepare(c.sql).statement;const run=async()=>{const out=[];while(await s.step()==='row')out.push(Array.from({length:s.columnCount},(_,i)=>s.column(i)));return out};s.bind(1,1n);assert.deepEqual(await run(),c.native.first.rows.map(r=>r.map(value)));s.reset();s.bind(1,2n);assert.deepEqual(await run(),c.native.afterResetRebind.rows.map(r=>r.map(value)))}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>server.close(e=>e?j(e):r()))}});


test('public UTF-16 INNER cases match pinned 3.53.4 multisource capture',async()=>{for(const [id,file] of [['utf16le-qualified','./fixtures/multisource-inner-oracle-utf16le.db'],['utf16be-star','./fixtures/multisource-inner-oracle-utf16be.db']]){const c=capture.cases.find(c=>c.id===id);assert.ok(c);const server=await serve(file);let db,s;try{db=await openFixture(new Request(`http://127.0.0.1:${server.address().port}/db`));s=db.prepare(c.sql).statement;assert.deepEqual(Array.from({length:s.columnCount},(_,i)=>{const m=s.columnMetadata(i);return{name:m.name,declType:m.declaredType,database:m.database,table:m.table,origin:m.origin}}),c.native.columns,id+' metadata');const actual=[];while(await s.step()==='row')actual.push(Array.from({length:s.columnCount},(_,i)=>s.column(i)));assert.deepEqual(actual,c.native.first.rows.map(r=>r.map(value)),id+' rows')}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>server.close(e=>e?j(e):r()))}}});


const upstreamCases=[['upstream-comma-on','./fixtures/multisource-inner-oracle-upstream-join-basic.db'],['upstream-inner-using-star','./fixtures/multisource-inner-oracle-upstream-join-basic.db'],['upstream-natural-left-collation','./fixtures/multisource-inner-oracle-upstream-join-collation.db']];
for(const [id,file] of upstreamCases)test(`public translated upstream ${id} matches pinned 3.53.4 capture`,async()=>{const c=capture.cases.find(c=>c.id===id);assert.ok(c);const server=await serve(file);let db,s;try{db=await openFixture(new Request(`http://127.0.0.1:${server.address().port}/db`));s=db.prepare(c.sql).statement;assert.deepEqual(Array.from({length:s.columnCount},(_,i)=>{const m=s.columnMetadata(i);return{name:m.name,declType:m.declaredType,database:m.database,table:m.table,origin:m.origin}}),c.native.columns,id+' metadata');const actual=[];while(await s.step()==='row')actual.push(Array.from({length:s.columnCount},(_,i)=>s.column(i)));assert.deepEqual(actual,c.native.first.rows.map(r=>r.map(value)),id+' rows')}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>server.close(e=>e?j(e):r()))}});

test('public joined compound arm matches pinned 3.53.4 multisource capture',async()=>{const c=capture.cases.find(c=>c.id==='compound-arm');assert.ok(c);const server=await serve();let db,s;try{db=await openFixture(new Request(`http://127.0.0.1:${server.address().port}/db`));s=db.prepare(c.sql).statement;assert.deepEqual(Array.from({length:s.columnCount},(_,i)=>{const m=s.columnMetadata(i);return{name:m.name,declType:m.declaredType,database:m.database,table:m.table,origin:m.origin}}),c.native.columns,c.id+' metadata');const actual=[];while(await s.step()==='row')actual.push(Array.from({length:s.columnCount},(_,i)=>s.column(i)));assert.deepEqual(actual,c.native.first.rows.map(r=>r.map(value)),c.id+' rows')}finally{try{s?.finalize()}catch{}try{db?.closeDeferred()}catch{}await new Promise((r,j)=>server.close(e=>e?j(e):r()))}});
