import test from 'node:test';import assert from 'node:assert/strict';
import {parseSql} from '../../src/internal/parse.ts';import {expandAndResolveSelect} from '../../src/internal/resolve.ts';
import {analyzeWhere,btreeLoops,sourceBit,wherePathSolver,logEstAdd,planWhere,WherePlanningUnsupportedError} from '../../src/internal/where-plan.ts';
import {physicalRowidIndex} from '../../src/internal/schema.ts';
const col=(name,type,extra={})=>Object.freeze({name,declaredType:type,affinity:type==='TEXT'?'text':type==='REAL'?'real':type==='BLOB'?'blob':'integer',defaultExpr:null,generatedExpr:null,defaultIndex:null,notNull:false,primaryKeyPosition:null,unique:false,collation:null,generatedStorage:null,checks:[],...extra});
function schema(){const id=col('id','INTEGER',{primaryKeyPosition:1}),a=col('a','TEXT',{collation:'NOCASE'}),b=col('b','REAL'),blob=col('blob','BLOB');const t={kind:'table',name:'t',tableName:'t',rootPage:2,sql:'',columns:Object.freeze([id,a,b,blob]),indexes:[],withoutRowid:false,primaryKey:Object.freeze([id]),storageKey:Object.freeze([]),checks:Object.freeze([]),foreignKeys:Object.freeze([]),referencedBy:Object.freeze([])};const i={kind:'index',name:'i_ab',tableName:'t',rootPage:3,sql:'',table:t,terms:Object.freeze([{column:a,expression:null,expressionSql:null,descending:false,collation:'NOCASE',nulls:null},{column:b,expression:null,expressionSql:null,descending:true,collation:null,nulls:null}].map(Object.freeze)),unique:false,origin:'create',physical:null};i.physical=physicalRowidIndex(i,'utf-8');t.indexes.push(i);Object.freeze(t.indexes);return {tables:new Map([['t',t]]),t,i,id,a,b,blob};}
const resolve=(sql,s)=>expandAndResolveSelect(parseSql(sql).statement,s);
test('production split/analyze commutes operands and derives rowid/range masks',()=>{const s=schema(),r=resolve("SELECT a FROM t WHERE 5 < id AND a COLLATE nocase = 'x' AND b <= 1.5",s),a=analyzeWhere(r);assert.equal(a.clause.terms.length,3);assert.equal(a.clause.terms[0].operator,'gt');assert.equal(a.clause.terms[0].originalIndexedOperand,'right');assert.equal(a.clause.terms[0].left.rowid,true);assert.equal(a.clause.terms[1].effectiveCollation,'nocase');assert.equal(a.clause.terms[2].rightAffinity,'real');const loops=btreeLoops(r.sources[0],0,a.clause,{forcedIndex:null,neededColumns:new Set([s.a,s.blob]),orderBy:[]});assert.ok(loops.some(x=>x.kind==='rowid'));const ix=loops.find(x=>x.kind==='index');assert.ok(ix);assert.equal(ix.capability.equalityPrefix.length,1);assert.equal(ix.capability.upper.bound,'upper-inclusive');assert.equal(ix.capability.covering,false);assert.equal(ix.capability.needsTableLookup,true);const onlyB=analyzeWhere(resolve('SELECT a FROM t WHERE b>1',s));const bLoop=btreeLoops(r.sources[0],0,onlyB.clause,{forcedIndex:null,neededColumns:new Set(),orderBy:[]});assert.deepEqual(bLoop.map(x=>x.kind),['table-scan']);const selected=planWhere(r,{neededColumns:[new Set([s.a,s.blob])],orderBy:[]});assert.equal(selected.path.loops[0].kind,'rowid');assert.equal(selected.path.loops[0].capability.rowidLower.term,selected.analysis.clause.terms[0]);});
test('gates NOT INDEXED, forced full index and pointless index; RIGHT/FULL fallback unchanged',()=>{const s=schema(),r=resolve('SELECT a FROM t',s),a=analyzeWhere(r);assert.deepEqual(btreeLoops(r.sources[0],0,a.clause,{forcedIndex:null,neededColumns:new Set(),orderBy:[]}).map(x=>x.kind),['table-scan']);assert.deepEqual(btreeLoops(r.sources[0],0,a.clause,{forcedIndex:null,neededColumns:new Set(),orderBy:[{sourceOrdinal:0,column:s.a,descending:false,collation:'nocase'}]}).map(x=>x.kind),['table-scan','index']);assert.deepEqual(btreeLoops(r.sources[0],0,a.clause,{forcedIndex:s.i,neededColumns:new Set(),orderBy:[]}).map(x=>x.kind),['index']);assert.deepEqual(btreeLoops(r.sources[0],0,a.clause,{forcedIndex:null,notIndexed:true,neededColumns:new Set(),orderBy:[]}).map(x=>x.kind),['table-scan']);const row=resolve('SELECT a FROM t WHERE id=1',s),rowAnalysis=analyzeWhere(row);assert.deepEqual(btreeLoops(row.sources[0],0,rowAnalysis.clause,{forcedIndex:null,notIndexed:true,neededColumns:new Set(),orderBy:[]}).map(x=>x.kind),['table-scan','rowid']);assert.throws(()=>btreeLoops(r.sources[0],0,a.clause,{forcedIndex:s.i,notIndexed:true,neededColumns:new Set(),orderBy:[]}),WherePlanningUnsupportedError);const rr=resolve('SELECT t.a FROM t RIGHT JOIN t AS u ON t.id=u.id',s);assert.deepEqual(analyzeWhere(rr),{clause:{split:'and',terms:[],outer:null},plannerEligible:false,fallback:'right-full'});});
test('resolved typed and NULL boundaries survive analysis across physical encodings',()=>{for(const encoding of ['utf-8','utf-16le','utf-16be']){const s=schema();const physical=physicalRowidIndex(s.i,encoding);assert.equal(physical.keyInfo.encoding,encoding);for(const [sql,affinity,operator] of [["SELECT a FROM t WHERE a='01'",'text','eq'],["SELECT a FROM t WHERE b=1",'integer','eq'],["SELECT a FROM t WHERE b=1.25",'real','eq'],["SELECT a FROM t WHERE blob=x'00ff'",'blob','eq'],["SELECT a FROM t WHERE a IS NULL",null,'is-null']]){const term=analyzeWhere(resolve(sql,s)).clause.terms[0];assert.equal(term.rightAffinity,affinity);assert.equal(term.operator,operator);}}});
test('LEFT provenance prerequisites and N-best LogEst path selection',()=>{const s=schema(),r=resolve('SELECT t.a FROM t LEFT JOIN t AS u ON u.a=t.a WHERE t.id>0',s),a=analyzeWhere(r),on=a.clause.terms.find(x=>x.origin.kind==='join-on');assert.ok(on);assert.equal(on.prereqRight,sourceBit(0));assert.equal(on.outerJoinSafe.mayOmitResidual,false);assert.equal(logEstAdd(10n,10n),20n);const mk=(source,n,prereq,cost,rows)=>Object.freeze({source,sourceOrdinal:n,prereq,capability:null,kind:'table-scan',setupCost:0n,runCost:cost,outputRows:rows,terms:Object.freeze([])});const p=wherePathSolver([[mk(r.sources[0],0,0n,20n,10n)],[mk(r.sources[1],1,sourceBit(0),5n,1n)]],2);assert.deepEqual(p.loops.map(x=>x.sourceOrdinal),[0,1]);});
