import { encodeSql, tokenize, type SqlToken } from "./tokenize.ts";
import { tokenIds } from "../generated/parser-tables.ts";
import { keywordTable } from "../generated/keyword-table.ts";
import { lemonParse, type LemonTrace, type LemonValue } from "./lemon-runtime.ts";

export type ExprNode={readonly kind:"tokens";readonly tokens:readonly SqlToken[];readonly reduction?:LemonValue<SqlToken>;readonly alias?:string};
export type OrderTermNode={readonly expr:ExprNode;readonly descending:boolean;readonly nulls:"first"|"last"|null};
export type SelectNode={readonly kind:"select";readonly result:readonly ExprNode[];readonly from:readonly SqlToken[];readonly where:ExprNode|null;readonly orderBy:readonly OrderTermNode[];readonly limit:ExprNode|null;readonly offset:ExprNode|null;readonly hasDistinct:boolean;readonly hasGroupBy:boolean;readonly hasHaving:boolean;readonly hasOrderBy:boolean;readonly hasLimit:boolean;readonly hasCompound:boolean;readonly hasSubquery:boolean;readonly tokens:readonly SqlToken[]};
export interface SchemaColumnDeclaration {readonly name:string;readonly declaredType:string|null;readonly defaultExpr:ExprNode|null;readonly generatedExpr:ExprNode|null;readonly notNull:boolean;readonly primaryKey:boolean;readonly unique:boolean;readonly collation:string|null;readonly generatedStorage:"stored"|"virtual"|null}
export interface SchemaIndexTermDeclaration {readonly expr:ExprNode;readonly descending:boolean;readonly collation:string|null;readonly nulls:"first"|"last"|null}
export type SchemaDdlNode={readonly kind:"create-table"|"create-index"|"create-view"|"create-trigger";readonly name:string|null;readonly tokens:readonly SqlToken[];readonly columns:readonly SchemaColumnDeclaration[];readonly withoutRowid:boolean;readonly indexTerms:readonly SchemaIndexTermDeclaration[];readonly tableName:string|null;readonly select:SelectNode|null;readonly indexWhere:ExprNode|null;readonly tableAsSelect:SelectNode|null;readonly primaryKey:readonly string[];readonly indexUnique:boolean};
export type ParsedStatement=SelectNode|SchemaDdlNode;
export interface ParseResult{readonly statement:ParsedStatement|null;readonly tailOffset:number;readonly tailCodeUnit:number;readonly lemon:LemonTrace<SqlToken>|null}
export class SqlParseError extends Error{}
const tokenKindNames:Partial<Record<SqlToken["kind"],keyof typeof tokenIds>>={id:"ID",integer:"INTEGER",float:"FLOAT",string:"STRING",blob:"BLOB",variable:"VARIABLE"};
const punctuationNames:Readonly<Record<string,keyof typeof tokenIds>>={";":"SEMI","(":"LP",")":"RP",",":"COMMA","=":"EQ","==":"EQ","!=":"NE","<>":"NE",">":"GT","<=":"LE","<":"LT",">=":"GE","+":"PLUS","-":"MINUS","*":"STAR","/":"SLASH","%":"REM","||":"CONCAT","&":"BITAND","|":"BITOR","~":"BITNOT","<<":"LSHIFT",">>":"RSHIFT",".":"DOT"};
function byteToCodeUnit(sql:string,byte:number){let b=0,i=0;for(const s of sql){if(b===byte)return i;b+=new TextEncoder().encode(s).length;i+=s.length;}if(b===byte)return i;throw Error("token ended inside UTF-8 scalar");}
function terminal(t:SqlToken):number|undefined{if(t.kind==="keyword"){const name=keywordTable.get(t.text.toUpperCase())as keyof typeof tokenIds|undefined;return name===undefined?undefined:tokenIds[name];}const name=tokenKindNames[t.kind]??punctuationNames[t.text];return name===undefined?undefined:tokenIds[name];}
function leaves(v:LemonValue<SqlToken>|undefined):SqlToken[]{if(!v)return[];return v.kind==="terminal"?(v.value?[v.value]:[]):v.children.flatMap(leaves);}
function find(v:LemonValue<SqlToken>|undefined,p:(s:string)=>boolean):LemonValue<SqlToken>|undefined{if(!v||v.kind==="terminal")return; if(p(v.signature))return v;for(const c of v.children){const x=find(c,p);if(x)return x;}}
function findAll(v:LemonValue<SqlToken>|undefined,p:(s:string)=>boolean,out:LemonValue<SqlToken>[]=[]):LemonValue<SqlToken>[] {if(!v||v.kind==="terminal")return out;if(p(v.signature))out.push(v);for(const c of v.children)findAll(c,p,out);return out;}
function direct(v:LemonValue<SqlToken>,prefix:string):LemonValue<SqlToken>|undefined{if(v.kind==="terminal")return;for(const child of v.children)if(child.kind==="reduction"&&child.signature.startsWith(prefix))return child;}
function sqlIdentifier(token:SqlToken|undefined):string{if(!token)throw new SqlParseError("generated schema name is missing");const value=token.text;if(value[0]==="["&&value.at(-1)==="]")return value.slice(1,-1);if((value[0]==='"'||value[0]==="`")&&value.at(-1)===value[0])return value.slice(1,-1).replaceAll(value[0]+value[0],value[0]);return value;}
function ddlColumns(root:LemonValue<SqlToken>):readonly SchemaColumnDeclaration[]{
 const entries=findAll(root,s=>s.startsWith("columnlist ::=")&&s.includes("columnname carglist")).map(declaration=>{
  const column=direct(declaration,"columnname ::="),args=direct(declaration,"carglist ::=");if(!column||!args)throw new SqlParseError("generated column action is incomplete");
  const nameNode=direct(column,"nm ::="),typeNode=direct(column,"typetoken ::="),nameToken=leaves(nameNode)[0],typeTokens=leaves(typeNode),constraints=findAll(args,s=>s.startsWith("ccons ::="));
  const expression=(prefix:string):ExprNode|null=>{const constraint=constraints.find(c=>c.kind==="reduction"&&c.signature.startsWith(prefix));if(!constraint)return null;const expr=find(constraint,s=>s.startsWith("expr ::="));if(expr)return{kind:"tokens",tokens:leaves(expr)};const tokens=leaves(constraint).slice(1);if(tokens[0]?.text==="("&&tokens.at(-1)?.text===")")tokens.splice(tokens.length-1,1),tokens.splice(0,1);if(!tokens.length)throw new SqlParseError("generated column expression is missing");return{kind:"tokens",tokens};};
  const has=(prefix:string)=>constraints.some(c=>c.kind==="reduction"&&c.signature.startsWith(prefix));
  const collate=constraints.find(c=>c.kind==="reduction"&&c.signature.startsWith("ccons ::= COLLATE"));
  const generated=constraints.find(c=>c.kind==="reduction"&&(c.signature.startsWith("ccons ::= GENERATED")||c.signature.startsWith("ccons ::= AS generated")));
  const generatedWords=generated?leaves(generated).map(t=>t.text.toUpperCase()):[];
  return{offset:nameToken?.startByte??0,value:Object.freeze({name:sqlIdentifier(nameToken),declaredType:typeTokens.length?typeTokens.map(t=>t.text).join(" "):null,defaultExpr:expression("ccons ::= DEFAULT"),generatedExpr:expression("ccons ::= GENERATED")??expression("ccons ::= AS generated"),notNull:has("ccons ::= NOT NULL"),primaryKey:has("ccons ::= PRIMARY KEY"),unique:has("ccons ::= UNIQUE"),collation:collate?sqlIdentifier(leaves(collate)[1]):null,generatedStorage:generated?(generatedWords.includes("STORED")?"stored":"virtual"):null})};
 });
 return Object.freeze(entries.sort((a,b)=>a.offset-b.offset).map(entry=>entry.value));
}
function selectAction(root:LemonValue<SqlToken>,all:readonly SqlToken[]):SelectNode{
 const one=findAll(root,s=>s.startsWith("oneselect ::= SELECT ")).at(-1);if(!one)throw new SqlParseError("generated SELECT action is not mapped");
 const from=find(one,s=>s.startsWith("from ::=")),fromList=from?find(from,s=>s.startsWith("seltablist ::=")):undefined,where=find(one,s=>s.startsWith("where_opt ::="));
 const result=findAll(one,s=>s==="selcollist ::= sclp scanpt expr scanpt as"||s==="selcollist ::= sclp scanpt STAR"||s==="selcollist ::= sclp scanpt nm DOT STAR").map(item=>{if(item.kind!=="reduction")throw new SqlParseError("generated result expression is missing");const expr=item.signature.endsWith("expr scanpt as")?item.children[2]:undefined;const tokens=expr?leaves(expr):item.children.slice(2).flatMap(leaves);if(!tokens.length)throw new SqlParseError("generated result expression is missing");const asNode=expr?item.children[4]:undefined,asTokens=leaves(asNode);const alias=asTokens.length?sqlIdentifier(asTokens.at(-1)):undefined;return{kind:"tokens",tokens,...(expr?{reduction:expr}:{}),...(alias===undefined?{}:{alias})} as ExprNode;}).sort((a,b)=>(a.tokens[0]?.startByte??0)-(b.tokens[0]?.startByte??0));
 const present=(prefix:string,empty:string)=>{const node=direct(one,prefix);return node?.kind==="reduction"&&node.signature!==empty;};
 const orderNode=direct(one,"orderby_opt ::="),sortList=orderNode?direct(orderNode,"sortlist ::="):undefined;
 const orderBy=sortList?findAll(sortList,s=>s.startsWith("sortlist ::=")).map(item=>{const expr=item.kind==="reduction"?item.children.find(c=>c.kind==="reduction"&&!c.signature.startsWith("sortlist ::=")&&!c.signature.startsWith("sortorder ::=")&&!c.signature.startsWith("nulls ::=")):undefined;if(!expr||expr.kind!=="reduction")throw new SqlParseError("generated ORDER BY expression is missing");const nullWords=leaves(direct(item,"nulls ::=")).map(t=>t.text.toUpperCase());return Object.freeze({expr:{kind:"tokens",tokens:leaves(expr),reduction:expr} as ExprNode,descending:leaves(direct(item,"sortorder ::=")).some(t=>t.text.toUpperCase()==="DESC"),nulls:nullWords.includes("FIRST")?"first":nullWords.includes("LAST")?"last":null});}).sort((a,b)=>(a.expr.tokens[0]?.startByte??0)-(b.expr.tokens[0]?.startByte??0)):[];
 const limitNode=find(one,s=>s.startsWith("limit_opt ::=")),limitExprs=limitNode?.kind==="reduction"?limitNode.children.filter(c=>c.kind==="reduction"):[];
 let limit:ExprNode|null=null,offset:ExprNode|null=null;if(limitExprs.length){const comma=leaves(limitNode).some(t=>t.text===",");const first={kind:"tokens",tokens:leaves(limitExprs[0]!),reduction:limitExprs[0]!} as ExprNode,second=limitExprs[1]?{kind:"tokens",tokens:leaves(limitExprs[1]),reduction:limitExprs[1]} as ExprNode:null;if(comma){offset=first;limit=second}else{limit=first;offset=second}}
 return{kind:"select",result,from:leaves(fromList),where:(()=>{const expr=where?find(where,s=>s.startsWith("expr ::=")):undefined;return expr?{kind:"tokens",tokens:leaves(expr),reduction:expr}:null;})(),orderBy:Object.freeze(orderBy),limit,offset,hasDistinct:present("distinct ::=","distinct ::="),hasGroupBy:present("groupby_opt ::=","groupby_opt ::="),hasHaving:present("having_opt ::=","having_opt ::="),hasOrderBy:present("orderby_opt ::=","orderby_opt ::="),hasLimit:present("limit_opt ::=","limit_opt ::="),hasCompound:findAll(root,s=>s.startsWith("multiselect_op ::=")).length>0,hasSubquery:findAll(root,s=>s==="seltablist ::= stl_prefix LP select RP as on_using"||s==="expr ::= LP select RP"||s==="expr ::= expr in_op LP select RP"||s==="expr ::= EXISTS LP select RP").length>0,tokens:all};
}
function schemaName(node:LemonValue<SqlToken>|undefined):string|null{const token=leaves(node)[0];return token?sqlIdentifier(token):null;}
function ddlAction(root:LemonValue<SqlToken>,all:readonly SqlToken[]):SchemaDdlNode|undefined{
 const candidates=[["TABLE","create_table ::="],["INDEX","cmd ::= createkw uniqueflag INDEX"],["VIEW","cmd ::= createkw temp VIEW"],["TRIGGER","cmd ::= createkw trigger_decl"]] as const;const matched=candidates.map(([kind,prefix])=>({kind,ddl:find(root,s=>s.startsWith(prefix))})).find(x=>x.ddl);if(!matched)return;const kindWord=matched.kind,ddl=matched.ddl!;
 const words=all.map(t=>t.text.toUpperCase()),options=findAll(root,s=>s.startsWith("table_option ::="));
 const sortlist=kindWord==="INDEX"?find(ddl,s=>s.startsWith("sortlist ::=")):undefined;
 const indexTerms=sortlist?findAll(sortlist,s=>s.startsWith("sortlist ::=")).map(item=>{const expr=direct(item,"expr ::=");if(!expr)throw new SqlParseError("generated index expression is missing");const exprTokens=leaves(expr),collateAt=exprTokens.findIndex(t=>t.text.toUpperCase()==="COLLATE"),nullWords=leaves(direct(item,"nulls ::=")).map(t=>t.text.toUpperCase());return Object.freeze({expr:{kind:"tokens",tokens:collateAt<0?exprTokens:exprTokens.slice(0,collateAt)} as ExprNode,descending:leaves(direct(item,"sortorder ::=")).some(t=>t.text.toUpperCase()==="DESC"),collation:collateAt<0?null:sqlIdentifier(exprTokens[collateAt+1]),nulls:nullWords.includes("FIRST")?"first":nullWords.includes("LAST")?"last":null});}).sort((a,b)=>(a.expr.tokens[0]?.startByte??0)-(b.expr.tokens[0]?.startByte??0)):[];
 const names=ddl.kind==="reduction"?ddl.children.filter(c=>c.kind==="reduction"&&c.signature.startsWith("nm ::=")):[];
 const selected=kindWord==="VIEW"?find(ddl,s=>s.startsWith("select ::=")):undefined,tableArgs=kindWord==="TABLE"?find(root,s=>s.startsWith("create_table_args ::= AS select")):undefined,tableSelected=tableArgs?find(tableArgs,s=>s.startsWith("select ::=")):undefined;
 const where=kindWord==="INDEX"?find(ddl,s=>s.startsWith("where_opt ::= WHERE")):undefined,whereExpr=where?find(where,s=>s.startsWith("expr ::=")):undefined;
 const tablePrimary=find(root,s=>s.startsWith("tcons ::= PRIMARY KEY")),primaryKey=tablePrimary?findAll(tablePrimary,s=>s.startsWith("sortlist ::=")).map(x=>direct(x,"expr ::=")).filter((x):x is LemonValue<SqlToken>=>!!x).map(x=>sqlIdentifier(leaves(x)[0])).reverse():[];
 return{kind:`create-${kindWord.toLowerCase()}` as SchemaDdlNode["kind"],name:schemaName(names[0]??find(ddl,s=>s.startsWith("nm ::="))),tokens:all,columns:kindWord==="TABLE"?ddlColumns(root):Object.freeze([]),withoutRowid:options.some(option=>option.kind==="reduction"&&option.signature.startsWith("table_option ::= WITHOUT")&&leaves(option).some(token=>token.text.toUpperCase()==="ROWID")),indexTerms:Object.freeze(indexTerms),tableName:kindWord==="INDEX"?schemaName(names.at(-1)):null,select:selected?selectAction(selected,leaves(selected)):null,indexWhere:whereExpr?{kind:"tokens",tokens:leaves(whereExpr)}:null,tableAsSelect:tableSelected?selectAction(tableSelected,leaves(tableSelected)):null,primaryKey:Object.freeze(primaryKey),indexUnique:kindWord==="INDEX"&&leaves(direct(ddl,"uniqueflag ::=")).some(t=>t.text.toUpperCase()==="UNIQUE")};
}
function deepFreeze<T>(value:T):T {if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as object))deepFreeze(child);Object.freeze(value);}return value;}
function productionAction(signature:string,children:readonly LemonValue<SqlToken>[]):ParsedStatement|undefined{
 // These are the bounded source-production semantic actions for the structures
 // this tranche claims. They execute while Lemon reduces cmd, not in a second
 // parser over accepted tokens.
 const root:LemonValue<SqlToken>={kind:"reduction",rule:-1,signature,children};
 const tokens=leaves(root);
 if(signature.startsWith("cmd ::= select"))return deepFreeze(selectAction(root,tokens));
 if(signature.startsWith("cmd ::= create_table")||signature.startsWith("cmd ::= createkw uniqueflag INDEX")||signature.startsWith("cmd ::= createkw temp VIEW")||signature.startsWith("cmd ::= createkw trigger_decl")){
  const ddl=ddlAction(root,tokens);if(ddl)return deepFreeze(ddl);
 }
}
function action(root:LemonValue<SqlToken>,tokens:readonly SqlToken[]):ParsedStatement{const cmd=find(root,s=>s.startsWith("cmd ::="));if(cmd?.kind==="reduction"&&cmd.semantic)return cmd.semantic as ParsedStatement;throw new SqlParseError(`near "${tokens[0]!.text}": syntax error`);}
export interface ParseLimits{readonly maxSqlBytes?:number;readonly maxWorkUnits?:number;readonly maxParserDepth?:number;readonly maxExpressionDepth?:number}
export function parseSql(sql:string,limits:number|ParseLimits=16*1024*1024):ParseResult{const options=typeof limits==="number"?{maxSqlBytes:limits}:limits;const maxSqlBytes=options.maxSqlBytes??16*1024*1024,maxWorkUnits=options.maxWorkUnits??10_000_000,maxParserDepth=options.maxParserDepth??2500,maxExpressionDepth=options.maxExpressionDepth??1000;let bytes:Uint8Array;try{bytes=encodeSql(sql);}catch(e){throw new SqlParseError((e as Error).message);}if(bytes.length>maxSqlBytes)throw new RangeError("SQL exceeds maxSqlBytes");const sig=tokenize(bytes).filter(t=>t.kind!=="space"&&t.kind!=="comment"&&t.kind!=="eof");if(!sig.length)return{statement:null,tailOffset:bytes.length,tailCodeUnit:sql.length,lemon:null};const illegal=sig.find(t=>t.kind==="illegal");if(illegal)throw new SqlParseError(`unrecognized token: "${illegal.text}"`);let depth=0,semi:SqlToken|undefined;for(const t of sig){if(t.text==="(")depth++;else if(t.text===")"){if(--depth<0)throw new SqlParseError('near ")": syntax error');}else if(t.text===";"&&depth===0){semi=t;break;}}if(depth)throw new SqlParseError("incomplete input");const tokens=sig.slice(0,semi?sig.indexOf(semi):undefined),ids=tokens.map((token,index)=>token.kind==="keyword"&&token.text.toUpperCase()==="REPLACE"&&tokens[index+1]?.text==="("?tokenIds.ID:terminal(token));if(ids.some(x=>x===undefined))throw new SqlParseError(`unrecognized token: "${tokens[ids.findIndex(x=>x===undefined)]!.text}"`);const sentinel:SqlToken={kind:"punct",startByte:semi?.startByte??bytes.length,endByte:semi?.endByte??bytes.length,text:";"},lemon=lemonParse([...ids as number[],tokenIds.SEMI,0],[...tokens,sentinel],{maxWorkUnits,maxParserDepth,maxExpressionDepth},productionAction);if(!lemon.accepted||!lemon.value)throw new SqlParseError(`near "${tokens.at(-1)?.text??""}": syntax error`);const statement=action(lemon.value,tokens),tailOffset=semi?.endByte??bytes.length;return{statement,tailOffset,tailCodeUnit:byteToCodeUnit(sql,tailOffset),lemon};}
