import { encodeSql, tokenize, type SqlToken } from "./tokenize.ts";
import { lemonTables, tokenIds } from "../generated/parser-tables.ts";
import { keywordTable } from "../generated/keyword-table.ts";
import { lemonParse, type LemonTrace, type LemonValue } from "./lemon-runtime.ts";

export type ExprNode={readonly kind:"tokens";readonly tokens:readonly SqlToken[];readonly reduction?:LemonValue<SqlToken>;readonly alias?:string};
export type OrderTermNode={readonly expr:ExprNode;readonly descending:boolean;readonly nulls:"first"|"last"|null};
export type CompoundOperator="union-all"|"union"|"intersect"|"except";
export type JoinFlags=Readonly<{inner:boolean;cross:boolean;natural:boolean;left:boolean;right:boolean;outer:boolean;error:boolean}>;
export type SourceItem=Readonly<{databaseName:string|null;tableName:string;alias:string|null;indexedBy:string|null;notIndexed:boolean;on:ExprNode|null;using:readonly string[]|null;joinFromLeft:JoinFlags;leftOfRightJoin:boolean;cursorId:null;table:null}>;
export type SourceList=readonly SqlToken[]&Readonly<{items:readonly SourceItem[];tokens:readonly SqlToken[]}>;
export type SelectArm={readonly result:readonly ExprNode[];readonly from:SourceList;readonly where:ExprNode|null;readonly hasDistinct:boolean;readonly hasGroupBy:boolean;readonly hasHaving:boolean;readonly origin:"select"|"values";readonly valuesRows:readonly (readonly ExprNode[])[]|null;readonly operatorFromPrior:CompoundOperator|null;readonly prior:number|null;readonly next:number|null};
export type SelectNode={readonly kind:"select";readonly result:readonly ExprNode[];readonly from:SourceList;readonly where:ExprNode|null;readonly groupBy:readonly ExprNode[];readonly having:ExprNode|null;readonly orderBy:readonly OrderTermNode[];readonly windowNames:readonly string[];readonly limit:ExprNode|null;readonly offset:ExprNode|null;readonly hasDistinct:boolean;readonly hasGroupBy:boolean;readonly hasHaving:boolean;readonly hasOrderBy:boolean;readonly hasLimit:boolean;readonly hasCompound:boolean;readonly hasValues:boolean;readonly hasSubquery:boolean;readonly arms:readonly SelectArm[];readonly tokens:readonly SqlToken[]};
export interface SchemaColumnDeclaration {readonly name:string;readonly declaredType:string|null;readonly defaultExpr:ExprNode|null;readonly generatedExpr:ExprNode|null;readonly notNull:boolean;readonly primaryKey:boolean;readonly unique:boolean;readonly collation:string|null;readonly generatedStorage:"stored"|"virtual"|null}
export interface SchemaIndexTermDeclaration {readonly expr:ExprNode;readonly descending:boolean;readonly collation:string|null;readonly nulls:"first"|"last"|null}
export type SchemaDdlNode={readonly kind:"create-table"|"create-index"|"create-view"|"create-trigger";readonly name:string|null;readonly tokens:readonly SqlToken[];readonly columns:readonly SchemaColumnDeclaration[];readonly withoutRowid:boolean;readonly indexTerms:readonly SchemaIndexTermDeclaration[];readonly tableName:string|null;readonly select:SelectNode|null;readonly indexWhere:ExprNode|null;readonly tableAsSelect:SelectNode|null;readonly primaryKey:readonly string[];readonly indexUnique:boolean;readonly hasUnsupportedConstraints:boolean};
export type ParsedStatement=SelectNode|SchemaDdlNode;
export interface ParseResult{readonly statement:ParsedStatement|null;readonly tailOffset:number;readonly tailCodeUnit:number;readonly lemon:LemonTrace<SqlToken>|null}
export class SqlParseError extends Error{}
const tokenKindNames:Partial<Record<SqlToken["kind"],keyof typeof tokenIds>>={id:"ID",integer:"INTEGER",float:"FLOAT",string:"STRING",blob:"BLOB",variable:"VARIABLE"};
const punctuationNames:Readonly<Record<string,keyof typeof tokenIds>>={";":"SEMI","(":"LP",")":"RP",",":"COMMA","=":"EQ","==":"EQ","!=":"NE","<>":"NE",">":"GT","<=":"LE","<":"LT",">=":"GE","+":"PLUS","-":"MINUS","*":"STAR","/":"SLASH","%":"REM","||":"CONCAT","&":"BITAND","|":"BITOR","~":"BITNOT","<<":"LSHIFT",">>":"RSHIFT",".":"DOT"};
function byteToCodeUnit(sql:string,byte:number){let b=0,i=0;for(const s of sql){if(b===byte)return i;b+=new TextEncoder().encode(s).length;i+=s.length;}if(b===byte)return i;throw Error("token ended inside UTF-8 scalar");}
function terminal(t:SqlToken):number|undefined{if(t.kind==="keyword"){const name=keywordTable.get(t.text.toUpperCase())as keyof typeof tokenIds|undefined;return name===undefined?undefined:tokenIds[name];}const name=tokenKindNames[t.kind]??punctuationNames[t.text];return name===undefined?undefined:tokenIds[name];}
/** Port of tokenize.c getToken()/analyze{Window,Over,Filter}Keyword(). */
function contextualTerminals(tokens:readonly SqlToken[]):readonly (number|undefined)[]{
 const raw=tokens.map(terminal),id=tokenIds.ID;
 const identifier=(token:number|undefined)=>token===id||token===tokenIds.STRING||token===tokenIds.JOIN_KW||token===tokenIds.WINDOW||token===tokenIds.OVER||(token!==undefined&&(lemonTables.fallback[token]??0)===id);
 const out:(number|undefined)[]=[];let previous=-1;
 for(let i=0;i<raw.length;i++){
  const token=raw[i],next=raw[i+1],afterNext=raw[i+2];let adapted=token;
  if(token===tokenIds.WINDOW)adapted=identifier(next)&&afterNext===tokenIds.AS?token:id;
  else if(token===tokenIds.OVER)adapted=previous===tokenIds.RP&&(next===tokenIds.LP||identifier(next))?token:id;
  else if(token===tokenIds.FILTER)adapted=previous===tokenIds.RP&&next===tokenIds.LP?token:id;
  out.push(adapted);previous=adapted??-1;
 }
 return out;
}
function leaves(v:LemonValue<SqlToken>|undefined):SqlToken[]{if(!v)return[];return v.kind==="terminal"?(v.value?[v.value]:[]):v.children.flatMap(leaves);}
function find(v:LemonValue<SqlToken>|undefined,p:(s:string)=>boolean):LemonValue<SqlToken>|undefined{if(!v||v.kind==="terminal")return; if(p(v.signature))return v;for(const c of v.children){const x=find(c,p);if(x)return x;}}
function findAll(v:LemonValue<SqlToken>|undefined,p:(s:string)=>boolean,out:LemonValue<SqlToken>[]=[]):LemonValue<SqlToken>[] {if(!v||v.kind==="terminal")return out;if(p(v.signature))out.push(v);for(const c of v.children)findAll(c,p,out);return out;}
function direct(v:LemonValue<SqlToken>,prefix:string):LemonValue<SqlToken>|undefined{if(v.kind==="terminal")return;for(const child of v.children)if(child.kind==="reduction"&&child.signature.startsWith(prefix))return child;}
function sqlIdentifier(token:SqlToken|undefined):string{if(!token)throw new SqlParseError("generated schema name is missing");const value=token.text;if(value[0]==="["&&value.at(-1)==="]")return value.slice(1,-1);if((value[0]==='"'||value[0]==="`")&&value.at(-1)===value[0])return value.slice(1,-1).replaceAll(value[0]+value[0],value[0]);return value;}
function ddlColumns(root:LemonValue<SqlToken>):readonly SchemaColumnDeclaration[]{
 const entries=findAll(root,s=>s.startsWith("columnlist ::=")&&s.includes("columnname carglist")).map(declaration=>{
  const column=direct(declaration,"columnname ::="),args=direct(declaration,"carglist ::=");if(!column||!args)throw new SqlParseError("generated column action is incomplete");
  const nameNode=direct(column,"nm ::="),typeNode=direct(column,"typetoken ::="),nameToken=leaves(nameNode)[0],rawTypeTokens=leaves(typeNode),generatedAt=rawTypeTokens.findIndex(token=>token.text.toUpperCase()==="GENERATED"),typeTokens=generatedAt<0?rawTypeTokens:rawTypeTokens.slice(0,generatedAt),constraints=findAll(args,s=>s.startsWith("ccons ::="));
  const expression=(prefix:string):ExprNode|null=>{const constraint=constraints.find(c=>c.kind==="reduction"&&c.signature.startsWith(prefix));if(!constraint)return null;const expr=find(constraint,s=>s.startsWith("expr ::="));if(expr)return{kind:"tokens",tokens:leaves(expr)};const tokens=leaves(constraint).slice(1);if(tokens[0]?.text==="("&&tokens.at(-1)?.text===")")tokens.splice(tokens.length-1,1),tokens.splice(0,1);if(!tokens.length)throw new SqlParseError("generated column expression is missing");return{kind:"tokens",tokens};};
  const has=(prefix:string)=>constraints.some(c=>c.kind==="reduction"&&c.signature.startsWith(prefix));
  const collate=constraints.find(c=>c.kind==="reduction"&&c.signature.startsWith("ccons ::= COLLATE"));
  const generated=constraints.find(c=>c.kind==="reduction"&&(c.signature.startsWith("ccons ::= GENERATED")||c.signature.startsWith("ccons ::= AS generated")));
  const generatedWords=generated?leaves(generated).map(t=>t.text.toUpperCase()):[];
  return{offset:nameToken?.startByte??0,value:Object.freeze({name:sqlIdentifier(nameToken),declaredType:typeTokens.length?typeTokens.map(t=>t.text).join(" "):null,defaultExpr:expression("ccons ::= DEFAULT"),generatedExpr:expression("ccons ::= GENERATED")??expression("ccons ::= AS generated"),notNull:has("ccons ::= NOT NULL"),primaryKey:has("ccons ::= PRIMARY KEY"),unique:has("ccons ::= UNIQUE"),collation:collate?sqlIdentifier(leaves(collate)[1]):null,generatedStorage:generated?(generatedWords.includes("STORED")?"stored":"virtual"):null})};
 });
 return Object.freeze(entries.sort((a,b)=>a.offset-b.offset).map(entry=>entry.value));
}
function selectListItems(root:LemonValue<SqlToken>):LemonValue<SqlToken>[] {const out:LemonValue<SqlToken>[]=[];const walk=(node:LemonValue<SqlToken>)=>{if(node.kind==="terminal")return;if(node!==root&&node.signature.startsWith("oneselect ::="))return;if(node.signature==="selcollist ::= sclp scanpt expr scanpt as"||node.signature==="selcollist ::= sclp scanpt STAR"||node.signature==="selcollist ::= sclp scanpt nm DOT STAR")out.push(node);for(const child of node.children)walk(child);};walk(root);return out;}
function expressionList(node:LemonValue<SqlToken>):readonly ExprNode[]{
 const out:ExprNode[]=[];
 const walk=(n:LemonValue<SqlToken>)=>{if(n.kind!=="reduction")return;for(const c of n.children){if(c.kind!=="reduction")continue;if(c.signature.startsWith("nexprlist ::="))walk(c);else if(c.signature.startsWith("expr ::=")||c.signature.startsWith("term ::="))out.push({kind:"tokens",tokens:leaves(c),reduction:c});}};
 walk(node);return Object.freeze(out);
}
const noJoin:JoinFlags=Object.freeze({inner:true,cross:false,natural:false,left:false,right:false,outer:false,error:false});
function joinFlags(node:LemonValue<SqlToken>|undefined):JoinFlags{const words=leaves(node).map(t=>t.text.toUpperCase()),names=words.filter(w=>w!=="JOIN"&&w!==",");return Object.freeze({inner:words.includes(",")||names.length===0||names.includes("INNER"),cross:names.includes("CROSS"),natural:names.includes("NATURAL"),left:names.includes("LEFT")||names.includes("FULL"),right:names.includes("RIGHT")||names.includes("FULL"),outer:names.includes("OUTER"),error:names.some(w=>!["INNER","CROSS","NATURAL","LEFT","RIGHT","FULL","OUTER"].includes(w))});}
function frozenSource(items:readonly SourceItem[],tokens:readonly SqlToken[]):SourceList{const out=[...tokens] as SqlToken[]&{items:readonly SourceItem[];tokens:readonly SqlToken[]};Object.defineProperties(out,{items:{value:Object.freeze([...items]),enumerable:true},tokens:{value:Object.freeze([...tokens]),enumerable:true}});return Object.freeze(out);}
/** Translation of parse.y stl_prefix/seltablist semantic actions and sqlite3SrcListShiftJoinType(). */
function sourceList(node:LemonValue<SqlToken>|undefined):SourceList{
 if(!node)return frozenSource([],[]);const items:SourceItem[]=[];
 const append=(list:LemonValue<SqlToken>):void=>{const prefix=direct(list,"stl_prefix ::=");if(prefix?.kind==="reduction"&&prefix.signature!=="stl_prefix ::="){const prior=direct(prefix,"seltablist ::=");if(prior)append(prior);}const reductions=list.kind==="reduction"?list.children.filter((c):c is LemonValue<SqlToken>&{kind:"reduction"}=>c.kind==="reduction"):[];const names=reductions.filter(c=>c.signature.startsWith("nm ::="));if(!names.length)throw new SqlParseError("generated FROM source name is missing");const first=sqlIdentifier(leaves(names[0])[0]),dbnm=reductions.find(c=>c.signature.startsWith("dbnm ::=")),dbToken=leaves(dbnm).find(t=>t.text!=="."),as=reductions.find(c=>c.signature.startsWith("as ::=")),asToken=leaves(as).find(t=>t.text.toUpperCase()!=="AS"),indexed=reductions.find(c=>c.signature.startsWith("indexed_by ::=")),indexedTokens=leaves(indexed),notIndexed=indexedTokens.some(t=>t.text.toUpperCase()==="NOT"),onUsing=reductions.find(c=>c.signature.startsWith("on_using ::=")),onExpr=onUsing?direct(onUsing,"expr ::="):undefined,idlist=onUsing?direct(onUsing,"idlist ::="):undefined,preceding=prefix?direct(prefix,"joinop ::="):undefined;const using=idlist?Object.freeze(leaves(idlist).filter(t=>t.text!==",").map(sqlIdentifier)):null;items.push(Object.freeze({databaseName:dbToken?first:null,tableName:dbToken?sqlIdentifier(dbToken):first,alias:asToken?sqlIdentifier(asToken):null,indexedBy:indexedTokens.length&&!notIndexed?sqlIdentifier(indexedTokens.at(-1)):null,notIndexed,on:onExpr?Object.freeze({kind:"tokens",tokens:Object.freeze(leaves(onExpr)),reduction:onExpr} as ExprNode):null,using,joinFromLeft:items.length?joinFlags(preceding):noJoin,leftOfRightJoin:false,cursorId:null,table:null}));};append(node);const rightmost=items.reduce((n,item,i)=>item.joinFromLeft.right?i:n,-1),shifted=rightmost<0?items:items.map((item,i)=>i<rightmost?Object.freeze({...item,leftOfRightJoin:true}):item);return frozenSource(shifted,leaves(node));
}
function armAction(one:LemonValue<SqlToken>,operatorFromPrior:CompoundOperator|null):Omit<SelectArm,"prior"|"next">{
 const from=find(one,s=>s.startsWith("from ::=")),fromList=from?find(from,s=>s.startsWith("seltablist ::=")):undefined,where=find(one,s=>s.startsWith("where_opt ::="));
 const result=selectListItems(one).map(item=>{if(item.kind!=="reduction")throw new SqlParseError("generated result expression is missing");const expr=item.signature.endsWith("expr scanpt as")?item.children[2]:undefined;const tokens=expr?leaves(expr):item.children.slice(2).flatMap(leaves);if(!tokens.length)throw new SqlParseError("generated result expression is missing");const asNode=expr?item.children[4]:undefined,asTokens=leaves(asNode);const alias=asTokens.length?sqlIdentifier(asTokens.at(-1)):undefined;return Object.freeze({kind:"tokens",tokens,...(expr?{reduction:expr}:{}),...(alias!==undefined?{alias}:{})} as ExprNode);}).sort((a,b)=>(a.tokens[0]?.startByte??0)-(b.tokens[0]?.startByte??0));
 const present=(prefix:string,empty:string)=>{const node=direct(one,prefix);return node?.kind==="reduction"&&node.signature!==empty;};
 const expr=where?find(where,s=>s.startsWith("expr ::=")):undefined;
 return{result:Object.freeze(result),from:sourceList(fromList),where:expr?Object.freeze({kind:"tokens",tokens:leaves(expr),reduction:expr} as ExprNode):null,hasDistinct:present("distinct ::=","distinct ::="),hasGroupBy:present("groupby_opt ::=","groupby_opt ::="),hasHaving:present("having_opt ::=","having_opt ::="),origin:"select",valuesRows:null,operatorFromPrior};
}
type ArmDraft=Omit<SelectArm,"prior"|"next">;
type SelectSemantic={readonly arms:readonly ArmDraft[];readonly rightmost:LemonValue<SqlToken>};
function semanticOf<T>(child:LemonValue<SqlToken>|undefined,owner:string):T {if(child?.kind!=="reduction"||child.semantic===undefined)throw new SqlParseError(`generated ${owner} child semantic is missing`);return child.semantic as T;}
function linkedArms(drafts:readonly ArmDraft[]):readonly SelectArm[]{return Object.freeze(drafts.map((arm,i)=>Object.freeze({...arm,prior:i?i-1:null,next:i+1<drafts.length?i+1:null})));}
function selectAction(semantic:SelectSemantic,all:readonly SqlToken[]):SelectNode{
 const one=semantic.rightmost,arms=linkedArms(semantic.arms),hasValues=arms.some(arm=>arm.origin==="values");
 // parse.y accepts this only through error recovery. ORDER/LIMIT tokens before a
 // later compound arm are never owned by the rightmost oneselect and must not be
 // silently dropped into a partial-arm program.
 if(arms.length>1){const rightmost=arms.at(-1)!.result[0]!.tokens[0]!.startByte;const misplaced=all.find(t=>t.startByte<rightmost&&(t.text.toUpperCase()==="ORDER"||t.text.toUpperCase()==="LIMIT"));if(misplaced)throw new SqlParseError(`${misplaced.text.toUpperCase()} BY clause should come after ${arms.at(-1)!.operatorFromPrior!.toUpperCase().replace("-"," ")} not before`);}
 const from=find(one,s=>s.startsWith("from ::=")),fromList=from?find(from,s=>s.startsWith("seltablist ::=")):undefined,where=find(one,s=>s.startsWith("where_opt ::="));
 const result=selectListItems(one).map(item=>{if(item.kind!=="reduction")throw new SqlParseError("generated result expression is missing");const expr=item.signature.endsWith("expr scanpt as")?item.children[2]:undefined;const tokens=expr?leaves(expr):item.children.slice(2).flatMap(leaves);if(!tokens.length)throw new SqlParseError("generated result expression is missing");const asNode=expr?item.children[4]:undefined,asTokens=leaves(asNode);const alias=asTokens.length?sqlIdentifier(asTokens.at(-1)):undefined;return{kind:"tokens",tokens,...(expr?{reduction:expr}:{}),...(alias===undefined?{}:{alias})} as ExprNode;}).sort((a,b)=>(a.tokens[0]?.startByte??0)-(b.tokens[0]?.startByte??0));
 const present=(prefix:string,empty:string)=>{const node=direct(one,prefix);return node?.kind==="reduction"&&node.signature!==empty;};
 const groupNode=direct(one,"groupby_opt ::="),groupList=groupNode?direct(groupNode,"nexprlist ::="):undefined,groupBy=groupList?expressionList(groupList):Object.freeze([] as ExprNode[]),havingNode=direct(one,"having_opt ::="),havingExpr=havingNode?direct(havingNode,"expr ::="):undefined;
 const windowClause=direct(one,"window_clause ::="),windowNames=windowClause?findAll(windowClause,s=>s.startsWith("windowdefn ::=")).map(node=>sqlIdentifier(leaves(node)[0]!)):[];
 const orderNode=direct(one,"orderby_opt ::="),sortList=orderNode?direct(orderNode,"sortlist ::="):undefined;
 const orderBy=sortList?findAll(sortList,s=>s.startsWith("sortlist ::=")).map(item=>{const expr=item.kind==="reduction"?item.children.find(c=>c.kind==="reduction"&&!c.signature.startsWith("sortlist ::=")&&!c.signature.startsWith("sortorder ::=")&&!c.signature.startsWith("nulls ::=")):undefined;if(!expr||expr.kind!=="reduction")throw new SqlParseError("generated ORDER BY expression is missing");const nullWords=leaves(direct(item,"nulls ::=")).map(t=>t.text.toUpperCase());return Object.freeze({expr:{kind:"tokens",tokens:leaves(expr),reduction:expr} as ExprNode,descending:leaves(direct(item,"sortorder ::=")).some(t=>t.text.toUpperCase()==="DESC"),nulls:nullWords.includes("FIRST")?"first":nullWords.includes("LAST")?"last":null});}).sort((a,b)=>(a.expr.tokens[0]?.startByte??0)-(b.expr.tokens[0]?.startByte??0)):[];
 const limitNode=find(one,s=>s.startsWith("limit_opt ::=")),limitExprs=limitNode?.kind==="reduction"?limitNode.children.filter(c=>c.kind==="reduction"):[];
 let limit:ExprNode|null=null,offset:ExprNode|null=null;if(limitExprs.length){const comma=leaves(limitNode).some(t=>t.text===",");const first={kind:"tokens",tokens:leaves(limitExprs[0]!),reduction:limitExprs[0]!} as ExprNode,second=limitExprs[1]?{kind:"tokens",tokens:leaves(limitExprs[1]),reduction:limitExprs[1]} as ExprNode:null;if(comma){offset=first;limit=second}else{limit=first;offset=second}}
 const left=arms[0]!;
 return{kind:"select",result:left.result,from:left.from,where:(()=>{const expr=where?find(where,s=>s.startsWith("expr ::=")):undefined;return expr?{kind:"tokens",tokens:leaves(expr),reduction:expr}:null;})(),groupBy,having:havingExpr?{kind:"tokens",tokens:leaves(havingExpr),reduction:havingExpr}:null,orderBy:Object.freeze(orderBy),windowNames:Object.freeze(windowNames),limit,offset,hasDistinct:present("distinct ::=","distinct ::="),hasGroupBy:present("groupby_opt ::=","groupby_opt ::="),hasHaving:present("having_opt ::=","having_opt ::="),hasOrderBy:present("orderby_opt ::=","orderby_opt ::="),hasLimit:present("limit_opt ::=","limit_opt ::="),hasCompound:arms.length>1,hasValues,hasSubquery:findAll(one,s=>s==="seltablist ::= stl_prefix LP select RP as on_using"||s==="expr ::= LP select RP"||s==="expr ::= expr in_op LP select RP"||s==="expr ::= EXISTS LP select RP").length>0,arms,tokens:all};
}
function schemaName(node:LemonValue<SqlToken>|undefined):string|null{const token=leaves(node)[0];return token?sqlIdentifier(token):null;}
function ddlAction(root:LemonValue<SqlToken>,all:readonly SqlToken[]):SchemaDdlNode|undefined{
 const candidates=[["TABLE","create_table ::="],["INDEX","cmd ::= createkw uniqueflag INDEX"],["VIEW","cmd ::= createkw temp VIEW"],["TRIGGER","cmd ::= createkw trigger_decl"]] as const;const matched=candidates.map(([kind,prefix])=>({kind,ddl:find(root,s=>s.startsWith(prefix))})).find(x=>x.ddl);if(!matched)return;const kindWord=matched.kind,ddl=matched.ddl!;
 const words=all.map(t=>t.text.toUpperCase()),options=findAll(root,s=>s.startsWith("table_option ::="));
 const sortlist=kindWord==="INDEX"?find(ddl,s=>s.startsWith("sortlist ::=")):undefined;
 const indexTerms=sortlist?findAll(sortlist,s=>s.startsWith("sortlist ::=")).map(item=>{const expr=direct(item,"expr ::=");if(!expr)throw new SqlParseError("generated index expression is missing");const exprTokens=leaves(expr),collateAt=exprTokens.findIndex(t=>t.text.toUpperCase()==="COLLATE"),nullWords=leaves(direct(item,"nulls ::=")).map(t=>t.text.toUpperCase());return Object.freeze({expr:{kind:"tokens",tokens:collateAt<0?exprTokens:exprTokens.slice(0,collateAt)} as ExprNode,descending:leaves(direct(item,"sortorder ::=")).some(t=>t.text.toUpperCase()==="DESC"),collation:collateAt<0?null:sqlIdentifier(exprTokens[collateAt+1]),nulls:nullWords.includes("FIRST")?"first":nullWords.includes("LAST")?"last":null});}).sort((a,b)=>(a.expr.tokens[0]?.startByte??0)-(b.expr.tokens[0]?.startByte??0)):[];
 const names=ddl.kind==="reduction"?ddl.children.filter(c=>c.kind==="reduction"&&c.signature.startsWith("nm ::=")):[];
 const selected=kindWord==="VIEW"?find(ddl,s=>s.startsWith("select ::=")):undefined,tableArgs=kindWord==="TABLE"?find(root,s=>s.startsWith("create_table_args ::= AS select")):undefined,tableSelected=tableArgs?find(tableArgs,s=>s.startsWith("select ::=")):undefined;
 const where=kindWord==="INDEX"?find(ddl,s=>s.startsWith("where_opt ::= WHERE")):undefined,whereExpr=where?find(where,s=>s.startsWith("expr ::=")):undefined;
 const tablePrimary=find(root,s=>s.startsWith("tcons ::= PRIMARY KEY")),primaryKey=tablePrimary?findAll(tablePrimary,s=>s.startsWith("sortlist ::=")).map(x=>direct(x,"expr ::=")).filter((x):x is LemonValue<SqlToken>=>!!x).map(x=>sqlIdentifier(leaves(x)[0])).reverse():[];
 return{kind:`create-${kindWord.toLowerCase()}` as SchemaDdlNode["kind"],name:schemaName(names[0]??find(ddl,s=>s.startsWith("nm ::="))),tokens:all,columns:kindWord==="TABLE"?ddlColumns(root):Object.freeze([]),withoutRowid:options.some(option=>option.kind==="reduction"&&option.signature.startsWith("table_option ::= WITHOUT")&&leaves(option).some(token=>token.text.toUpperCase()==="ROWID")),indexTerms:Object.freeze(indexTerms),tableName:kindWord==="INDEX"?schemaName(names.at(-1)):null,select:selected?semanticOf<SelectNode>(selected,"view select"):null,indexWhere:whereExpr?{kind:"tokens",tokens:leaves(whereExpr)}:null,tableAsSelect:tableSelected?semanticOf<SelectNode>(tableSelected,"table AS select"):null,primaryKey:Object.freeze(primaryKey),indexUnique:kindWord==="INDEX"&&leaves(direct(ddl,"uniqueflag ::=")).some(t=>t.text.toUpperCase()==="UNIQUE"),hasUnsupportedConstraints:kindWord==="TABLE"&&findAll(root,s=>s.startsWith("ccons ::= CHECK")||s.startsWith("ccons ::= REFERENCES")||s.startsWith("tcons ::= CHECK")||s.startsWith("tcons ::= FOREIGN KEY")).length>0};
}
function deepFreeze<T>(value:T):T {if(value&&typeof value==="object"&&!Object.isFrozen(value)){for(const child of Object.values(value as object))deepFreeze(child);Object.freeze(value);}return value;}
function productionAction(signature:string,children:readonly LemonValue<SqlToken>[]):unknown{
 const root:LemonValue<SqlToken>={kind:"reduction",rule:-1,signature,children};
 if(signature==="values ::= VALUES LP nexprlist RP"){
  const list=direct(root,"nexprlist ::=");if(!list)throw new SqlParseError("generated VALUES row is missing");return Object.freeze([expressionList(list)]);
 }
 if(signature==="mvalues ::= values COMMA LP nexprlist RP"||signature==="mvalues ::= mvalues COMMA LP nexprlist RP"){
  const prior=semanticOf<readonly (readonly ExprNode[])[]>(children[0],"mvalues");const list=children[3];if(list?.kind!=="reduction")throw new SqlParseError("generated VALUES row is missing");return Object.freeze([...prior,expressionList(list)]);
 }
 if(signature==="oneselect ::= values"||signature==="oneselect ::= mvalues"){
  const rows=semanticOf<readonly (readonly ExprNode[])[]>(children[0],"oneselect VALUES");const arm:ArmDraft=Object.freeze({result:rows[0]!,from:sourceList(undefined),where:null,hasDistinct:false,hasGroupBy:false,hasHaving:false,origin:"values",valuesRows:rows,operatorFromPrior:null});return Object.freeze({arms:Object.freeze([arm]),rightmost:root} as SelectSemantic);
 }
 if(signature.startsWith("oneselect ::= SELECT "))return Object.freeze({arms:Object.freeze([Object.freeze(armAction(root,null))]),rightmost:root} as SelectSemantic);
 if(signature==="selectnowith ::= oneselect")return semanticOf<SelectSemantic>(children[0],"selectnowith");
 if(signature==="selectnowith ::= selectnowith multiselect_op oneselect"){
  const left=semanticOf<SelectSemantic>(children[0],"compound left"),right=semanticOf<SelectSemantic>(children[2],"compound right");
  const words=leaves(children[1]).map(t=>t.text.toUpperCase()).join(" "),operator:CompoundOperator=words==="UNION ALL"?"union-all":words==="UNION"?"union":words==="INTERSECT"?"intersect":"except";
  if(right.arms.length!==1)throw new SqlParseError("generated compound right arm is incomplete");const arm=Object.freeze({...right.arms[0]!,operatorFromPrior:operator});return Object.freeze({arms:Object.freeze([...left.arms,arm]),rightmost:right.rightmost} as SelectSemantic);
 }
 if(signature==="select ::= selectnowith"||signature==="select ::= WITH wqlist selectnowith"||signature==="select ::= WITH RECURSIVE wqlist selectnowith"){
  const child=children.at(-1);return deepFreeze(selectAction(semanticOf<SelectSemantic>(child,"select"),leaves(root)));
 }
 if(signature.startsWith("cmd ::= select"))return semanticOf<SelectNode>(children[0],"cmd select");
 const tokens=leaves(root);
 if(signature.startsWith("cmd ::= create_table")||signature.startsWith("cmd ::= createkw uniqueflag INDEX")||signature.startsWith("cmd ::= createkw temp VIEW")||signature.startsWith("cmd ::= createkw trigger_decl")){
  const ddl=ddlAction(root,tokens);if(ddl)return deepFreeze(ddl);
 }
}
function action(root:LemonValue<SqlToken>,tokens:readonly SqlToken[]):ParsedStatement{const cmd=find(root,s=>s.startsWith("cmd ::="));if(cmd?.kind==="reduction"&&cmd.semantic)return cmd.semantic as ParsedStatement;throw new SqlParseError(`near "${tokens[0]!.text}": syntax error`);}
export interface ParseLimits{readonly maxSqlBytes?:number;readonly maxWorkUnits?:number;readonly maxParserDepth?:number;readonly maxExpressionDepth?:number}
export function parseSql(sql:string,limits:number|ParseLimits=16*1024*1024):ParseResult{const options=typeof limits==="number"?{maxSqlBytes:limits}:limits;const maxSqlBytes=options.maxSqlBytes??16*1024*1024,maxWorkUnits=options.maxWorkUnits??10_000_000,maxParserDepth=options.maxParserDepth??2500,maxExpressionDepth=options.maxExpressionDepth??1000;let bytes:Uint8Array;try{bytes=encodeSql(sql);}catch(e){throw new SqlParseError((e as Error).message);}if(bytes.length>maxSqlBytes)throw new RangeError("SQL exceeds maxSqlBytes");const sig=tokenize(bytes).filter(t=>t.kind!=="space"&&t.kind!=="comment"&&t.kind!=="eof");if(!sig.length)return{statement:null,tailOffset:bytes.length,tailCodeUnit:sql.length,lemon:null};const illegal=sig.find(t=>t.kind==="illegal");if(illegal)throw new SqlParseError(`unrecognized token: "${illegal.text}"`);let depth=0,semi:SqlToken|undefined;for(const t of sig){if(t.text==="(")depth++;else if(t.text===")"){if(--depth<0)throw new SqlParseError('near ")": syntax error');}else if(t.text===";"&&depth===0){semi=t;break;}}if(depth)throw new SqlParseError("incomplete input");const tokens=sig.slice(0,semi?sig.indexOf(semi):undefined),ids=contextualTerminals(tokens);if(ids.some(x=>x===undefined))throw new SqlParseError(`unrecognized token: "${tokens[ids.findIndex(x=>x===undefined)]!.text}"`);const sentinel:SqlToken={kind:"punct",startByte:semi?.startByte??bytes.length,endByte:semi?.endByte??bytes.length,text:";"},lemon=lemonParse([...ids as number[],tokenIds.SEMI,0],[...tokens,sentinel],{maxWorkUnits,maxParserDepth,maxExpressionDepth},productionAction);if(!lemon.accepted||!lemon.value){const at=lemon.errorInput??tokens.length,token=tokens[at];throw new SqlParseError(token?`near "${token.text}": syntax error`:"incomplete input");}const statement=action(lemon.value,tokens),tailOffset=semi?.endByte??bytes.length;return{statement,tailOffset,tailCodeUnit:byteToCodeUnit(sql,tailOffset),lemon};}
